Repository DeveloperAcademy-POSTECH/MacC-Team-Maddori.Apple, pull requests merged in 2022-11, with the labels that each got.

#61 [ADD] SelectFeedbackMemberView 완성
  Maddori.Apple/Maddori.Apple.xcodeproj/project.pbxproj
  Maddori.Apple/Maddori.Apple/Global/Extension/UILabel+Extension.swift
  Maddori.Apple/Maddori.Apple/Global/Literal/TextLiteral.swift
  Maddori.Apple/Maddori.Apple/Global/UIComponent/MemberCollectionView.swift
  Maddori.Apple/Maddori.Apple/Global/UIComponent/MemberCollectionViewCell.swift
  Maddori.Apple/Maddori.Apple/Screen/SelectFeedbackMember/SelectFeedbackMemberViewController.swift
Labels: ✨ Feature

#59 [ADD] InProgressViewController UI 완성
  Maddori.Apple/Maddori.Apple.xcodeproj/project.pbxproj
  Maddori.Apple/Maddori.Apple/Global/Literal/SizeLiteral.swift
  Maddori.Apple/Maddori.Apple/Global/Literal/TextLiteral.swift
  Maddori.Apple/Maddori.Apple/Global/Resource/Assets.xcassets/AppIcon.appiconset/Contents.json
  Maddori.Apple/Maddori.Apple/Network/Model/Response/Keyword/Keyword.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/HomeViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/UIComponent/KeywordCollectionViewCell.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/UIComponent/KeywordCollectionViewFlowLayout.swift
  Maddori.Apple/Maddori.Apple/Screen/InProgress/InProgressViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/InProgress/SectionHeaderView.swift
Labels: ✨ Feature

#62 [CHORE] TestFlight를 위해 작업했던 내용들을 develop에 머지후 정리합니다.
  Maddori.Apple/Maddori.Apple.xcodeproj/project.pbxproj
  Maddori.Apple/Maddori.Apple/Global/Extension/Encodable+Extension.swift
  Maddori.Apple/Maddori.Apple/Global/Literal/TextLiteral.swift
  Maddori.Apple/Maddori.Apple/Global/Resource/Assets.xcassets/AppIcon.appiconset/Contents.json
  Maddori.Apple/Maddori.Apple/Global/Resource/Assets.xcassets/AppIcon.appiconset/keygoAppIcon.png
  Maddori.Apple/Maddori.Apple/Global/UIComponent/Button/BackButton.swift
  Maddori.Apple/Maddori.Apple/Global/UIComponent/Button/CloseButton.swift
  Maddori.Apple/Maddori.Apple/Global/UIComponent/Button/FeedbackTypeButtonView.swift
  Maddori.Apple/Maddori.Apple/Global/UIComponent/Button/MainButton.swift
  Maddori.Apple/Maddori.Apple/Global/UIComponent/CollectionView/KeywordCollectionViewCell.swift
  Maddori.Apple/Maddori.Apple/Global/UIComponent/CollectionView/KeywordCollectionViewFlowLayout.swift
  Maddori.Apple/Maddori.Apple/Global/UIComponent/CollectionView/MemberCollectionView.swift
  Maddori.Apple/Maddori.Apple/Global/UIComponent/CollectionView/MemberCollectionViewCell.swift
  Maddori.Apple/Maddori.Apple/Global/UIComponent/CollectionView/SectionHeaderView.swift
  Maddori.Apple/Maddori.Apple/Global/UIComponent/ExitButton.swift
  Maddori.Apple/Maddori.Apple/Global/UIComponent/TextField/FeedbackTextView.swift
  Maddori.Apple/Maddori.Apple/Global/UIComponent/TextField/KigoTextField.swift
  Maddori.Apple/Maddori.Apple/Global/UIComponent/View/KeywordLabel.swift
  Maddori.Apple/Maddori.Apple/Global/UIComponent/View/LabelButtonView.swift
  Maddori.Apple/Maddori.Apple/Network/Keyword/Keyword.swift
  Maddori.Apple/Maddori.Apple/Network/Model/Request/SampleDTO.swift
  Maddori.Apple/Maddori.Apple/Network/Model/Response/Sample.swift
  Maddori.Apple/Maddori.Apple/Network/ReflectionInfo/ReflectionInfoModel.swift
  Maddori.Apple/Maddori.Apple/Screen/FromTo/FromToViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/AddFeedbackContent/AddFeedbackContentViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/AddFeedbackMember/AddFeedbackMemberViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/AddReflection/AddReflectionViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/AddReflection/UIComponent/ReflectionNameView.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/HomeView/HomeViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/InProgress/InProgressViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/ReflectionInfo/ReflectionInfoViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/ReflectionInfo/UIComponent/StartSuggestionView.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/SelectFeedbackMember/SelectFeedbackMemberViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/StartReflection/StartReflectionViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/StartReflection/UIComponent/CustomVisualEffectView.swift
  Maddori.Apple/Maddori.Apple/Screen/Main/MainViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/MyBox/sample2
  Maddori.Apple/Maddori.Apple/Screen/MyReflection/sample1
Labels: 🛠 Chore

#66 [ADD] 보관함 View 팀원 선택 CollectionView 추가
  Maddori.Apple/Maddori.Apple.xcodeproj/project.pbxproj
  Maddori.Apple/Maddori.Apple/Global/Extension/UIView+Extension.swift
  Maddori.Apple/Maddori.Apple/Global/Literal/TextLiteral.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/AddReflection/AddReflectionViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/MyBox/Cell/MyBoxMemberCollectionViewCell.swift
  Maddori.Apple/Maddori.Apple/Screen/MyBox/MyBoxViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/MyBox/sample2
Labels: ✨ Feature, 🏖 Relax

#68 [ADD] 내가 작성한 피드백의 상세 화면 구현
  Maddori.Apple/Maddori.Apple.xcodeproj/project.pbxproj
  Maddori.Apple/Maddori.Apple/Global/Literal/TextLiteral.swift
  Maddori.Apple/Maddori.Apple/Global/UIComponent/Button/FeedbackTypeButtonView.swift
  Maddori.Apple/Maddori.Apple/Network/FeedbackFromMe/FeedbackFromMeModel.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/AddFeedbackContent/AddFeedbackContentViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/MyBox/FeedbackFromMeDetail/FeedbackFromMeDetailViewController.swift
Labels: ✨ Feature, 👏 Improvement

#67 [ADD] 보관함 Feedback CollectionView 생성
  Maddori.Apple/Maddori.Apple.xcodeproj/project.pbxproj
  Maddori.Apple/Maddori.Apple/Global/Extension/UILabel+Extension.swift
  Maddori.Apple/Maddori.Apple/Global/Literal/ImageLiteral.swift
  Maddori.Apple/Maddori.Apple/Network/Feedback/Feedback.swift
  Maddori.Apple/Maddori.Apple/Network/ReflectionInfo/ReflectionInfoModel.swift
  Maddori.Apple/Maddori.Apple/Screen/MyBox/Cell/MyFeedbackCollectionViewCell.swift
  Maddori.Apple/Maddori.Apple/Screen/MyBox/Cell/MyFeedbackHeaderView.swift
  Maddori.Apple/Maddori.Apple/Screen/MyBox/MyBoxViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/MyBox/UIComponent/MyFeedbackCollectionView.swift
Labels: ✨ Feature, 🏖 Relax

#71 [ADD] FeedBack CollectionView Divider 추가
  Maddori.Apple/Maddori.Apple/Network/Feedback/Feedback.swift
  Maddori.Apple/Maddori.Apple/Screen/MyBox/Cell/MyFeedbackCollectionViewCell.swift
  Maddori.Apple/Maddori.Apple/Screen/MyBox/Cell/MyFeedbackHeaderView.swift
  Maddori.Apple/Maddori.Apple/Screen/MyBox/MyBoxViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/MyBox/UIComponent/MyFeedbackCollectionView.swift
Labels: ✨ Feature, 👏 Improvement

#80 [CHORE] Stop만 있을 때 안뜨는 문제 해결
  Maddori.Apple/Maddori.Apple/Screen/MyBox/UIComponent/MyFeedbackCollectionView.swift
Labels: 🙏 ASAP, 🛠 Chore

#76 [ADD] 나의회고 자세한 회고 부분 뷰 구현
  Maddori.Apple/Maddori.Apple.xcodeproj/project.pbxproj
  Maddori.Apple/Maddori.Apple/Screen/MyReflection/Saved/MyReflectionDetailTableViewCell.swift
  Maddori.Apple/Maddori.Apple/Screen/MyReflection/Saved/MyReflectionDetailViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/MyReflection/Saved/SegmentedControl.swift
Labels: ✨ Feature, 🏖 Relax

#78 [ADD] Custom Alert 컴포넌트 구현
  Maddori.Apple/Maddori.Apple.xcodeproj/project.pbxproj
  Maddori.Apple/Maddori.Apple/Global/Extension/UIViewController+Extension.swift
  Maddori.Apple/Maddori.Apple/Global/Literal/TextLiteral.swift
  Maddori.Apple/Maddori.Apple/Global/UIComponent/View/AlertViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/MyBox/FeedbackFromMeDetail/FeedbackFromMeDetailViewController.swift
Labels: ✨ Feature, 👏 Improvement

#73 [ADD] 나의 회고 탭의 맨 처음 페이지 UI
  Maddori.Apple/Maddori.Apple.xcodeproj/project.pbxproj
  Maddori.Apple/Maddori.Apple/Global/Extension/UIFont+Extension.swift
  Maddori.Apple/Maddori.Apple/Global/Literal/ImageLiteral.swift
  Maddori.Apple/Maddori.Apple/Global/Literal/TextLiteral.swift
  Maddori.Apple/Maddori.Apple/Network/Reflection/Reflection.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/InProgress/InProgressViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/MyReflection/Main/MyReflectionMainViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/MyReflection/Main/ReflectionCollectionViewHeader.swift
  Maddori.Apple/Maddori.Apple/Screen/MyReflection/Main/TotalReflectionCell.swift
  Maddori.Apple/Maddori.Apple/Screen/MyReflection/sample1
Labels: ✨ Feature, 👏 Improvement

#86 [CHORE] AddFeedbackMember에서 멤버 리스트에 작성자가 포함되는 문제 해결
  Maddori.Apple/Maddori.Apple.xcodeproj/project.pbxproj
  Maddori.Apple/Maddori.Apple/Global/UIComponent/CollectionView/MemberCollectionView.swift
  Maddori.Apple/Maddori.Apple/Network/Member/Member.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/AddFeedbackMember/AddFeedbackMemberViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/SelectFeedbackMember/SelectFeedbackMemberViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/MyBox/MyBox/Cell/MyBoxMemberCollectionViewCell.swift
  Maddori.Apple/Maddori.Apple/Screen/MyBox/MyBox/Cell/MyFeedbackCollectionViewCell.swift
  Maddori.Apple/Maddori.Apple/Screen/MyBox/MyBox/Cell/MyFeedbackHeaderView.swift
  Maddori.Apple/Maddori.Apple/Screen/MyBox/MyBox/MyBoxViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/MyBox/MyBox/UIComponent/MyFeedbackCollectionView.swift
  Maddori.Apple/Maddori.Apple/Screen/MyReflection/Main/TotalReflectionCell.swift
Labels: ✨ Feature

#89 [CHORE] #85 PR에 미반영된 컨플릭트 반영하는 PR
  Maddori.Apple/Maddori.Apple/Global/Literal/ImageLiteral.swift
  Maddori.Apple/Maddori.Apple/Screen/MyBox/MyBox/Cell/MyFeedbackCollectionViewCell.swift
  Maddori.Apple/Maddori.Apple/Screen/MyReflection/Main/TotalReflectionCell.swift
  Maddori.Apple/Maddori.Apple/Screen/MyReflection/Saved/MyReflectionDetailTableViewCell.swift
Labels: 🙏 ASAP, 🛠 Chore

#92 [ADD] 커스텀 탭바 생성 및 연결
  Maddori.Apple/Maddori.Apple.xcodeproj/project.pbxproj
  Maddori.Apple/Maddori.Apple/Global/Extension/UITabBar+Extension.swift
  Maddori.Apple/Maddori.Apple/Global/Literal/ImageLiteral.swift
  Maddori.Apple/Maddori.Apple/Global/Literal/SizeLiteral.swift
  Maddori.Apple/Maddori.Apple/Global/Literal/TextLiteral.swift
  Maddori.Apple/Maddori.Apple/Global/Resource/Assets.xcassets/Docs.imageset/Contents.json
  Maddori.Apple/Maddori.Apple/Global/Resource/Assets.xcassets/Docs.imageset/Docs.svg
  Maddori.Apple/Maddori.Apple/Global/Resource/Assets.xcassets/Home.imageset/Contents.json
  Maddori.Apple/Maddori.Apple/Global/Resource/Assets.xcassets/Home.imageset/Home.svg
  Maddori.Apple/Maddori.Apple/Global/Resource/Assets.xcassets/Person.imageset/Contents.json
  Maddori.Apple/Maddori.Apple/Global/Resource/Assets.xcassets/Person.imageset/Person.svg
  Maddori.Apple/Maddori.Apple/Global/Supports/SceneDelegate.swift
  Maddori.Apple/Maddori.Apple/Global/UIComponent/TabBar/CustomTabBarController.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/HomeView/HomeViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/MyBox/MyBox/MyBoxViewController.swift
Labels: 🙏 ASAP

#98 [ADD] 내가 받은 피드백 디테일 뷰 구현
  Maddori.Apple/Maddori.Apple.xcodeproj/project.pbxproj
  Maddori.Apple/Maddori.Apple/Global/Literal/TextLiteral.swift
  Maddori.Apple/Maddori.Apple/Global/Supports/SceneDelegate.swift
  Maddori.Apple/Maddori.Apple/Network/FeedbackToMe/FeedbackToMeModel.swift
  Maddori.Apple/Maddori.Apple/Screen/MyReflection/FeedbackToMeDetail/FeedbackToMeDetailViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/MyReflection/Saved/CustomSegmentControl.swift
  Maddori.Apple/Maddori.Apple/Screen/MyReflection/Saved/MyReflectionDetailViewController.swift
Labels: ✨ Feature, 🙏 ASAP

#99 [FEAT] 전체적인 App Flow 연결
  Maddori.Apple/Maddori.Apple/Global/Base/BaseTextFieldViewController.swift
  Maddori.Apple/Maddori.Apple/Global/Extension/UIViewController+Extension.swift
  Maddori.Apple/Maddori.Apple/Global/Supports/SceneDelegate.swift
  Maddori.Apple/Maddori.Apple/Global/UIComponent/TabBar/CustomTabBarController.swift
  Maddori.Apple/Maddori.Apple/Global/UIComponent/View/AlertViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/AddFeedbackContent/AddFeedbackContentViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/AddFeedbackMember/AddFeedbackMemberViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/AddReflection/AddReflectionViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/HomeView/HomeViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/Login/LoginViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/MyBox/EditFeedbackFromMe/EditFeedbackFromMeViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/MyBox/FeedbackFromMeDetail/FeedbackFromMeDetailViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/MyBox/MyBox/MyBoxViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/MyBox/MyBox/UIComponent/MyFeedbackCollectionView.swift
  Maddori.Apple/Maddori.Apple/Screen/MyReflection/FeedbackToMeDetail/FeedbackToMeDetailViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/MyReflection/Main/MyReflectionMainViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/MyReflection/Saved/MyReflectionDetailViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/Setup/CreateTeamViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/Setup/JoinTeamViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/Setup/SetupNicknameViewController.swift
Labels: ✨ Feature, 🙏 ASAP

#101 [ADD] API 연결을 위한 model 생성
  Maddori.Apple/Maddori.Apple.xcodeproj/project.pbxproj
  Maddori.Apple/Maddori.Apple/Global/UIComponent/View/ToastContentView.swift
  Maddori.Apple/Maddori.Apple/Network/Model/BaseModel.swift
  Maddori.Apple/Maddori.Apple/Network/Model/Feedback/Feedback.swift
  Maddori.Apple/Maddori.Apple/Network/Model/FeedbackFromMe/FeedbackFromMeModel.swift
  Maddori.Apple/Maddori.Apple/Network/Model/FeedbackToMe/FeedbackToMeModel.swift
  Maddori.Apple/Maddori.Apple/Network/Model/Keyword/Keyword.swift
  Maddori.Apple/Maddori.Apple/Network/Model/Member/Member.swift
  Maddori.Apple/Maddori.Apple/Network/Model/Reflection/Reflection.swift
  Maddori.Apple/Maddori.Apple/Network/Model/ReflectionInfo/ReflectionInfoModel.swift
  Maddori.Apple/Maddori.Apple/Network/Reqeust/DTO/AddReflectionDTO.swift
  Maddori.Apple/Maddori.Apple/Network/Reqeust/DTO/CreateTeamDTO.swift
  Maddori.Apple/Maddori.Apple/Network/Reqeust/DTO/FeedBackContentDTO.swift
  Maddori.Apple/Maddori.Apple/Network/Reqeust/DTO/JoinTeamDTO.swift
  Maddori.Apple/Maddori.Apple/Network/Reqeust/DTO/LoginDTO.swift
  Maddori.Apple/Maddori.Apple/Network/Response/AddReflectionResponse.swift
  Maddori.Apple/Maddori.Apple/Network/Response/AllCertainTypeFeedBackResponse.swift
  Maddori.Apple/Maddori.Apple/Network/Response/AllFeedBackResponse.swift
  Maddori.Apple/Maddori.Apple/Network/Response/AllReflectionResponse.swift
  Maddori.Apple/Maddori.Apple/Network/Response/CertainTeamDetailResponse.swift
  Maddori.Apple/Maddori.Apple/Network/Response/CreateTeamResponse.swift
  Maddori.Apple/Maddori.Apple/Network/Response/CurrentMemberResponse.swift
  Maddori.Apple/Maddori.Apple/Network/Response/CurrentReflectionResponse.swift
  Maddori.Apple/Maddori.Apple/Network/Response/EditFeedBackResponse.swift
  Maddori.Apple/Maddori.Apple/Network/Response/FeedBackContentResponse.swift
  Maddori.Apple/Maddori.Apple/Network/Response/FeedBackInfoResponse.swift
  Maddori.Apple/Maddori.Apple/Network/Response/FeedBackResponse.swift
  Maddori.Apple/Maddori.Apple/Network/Response/JoinTeamResponse.swift
  Maddori.Apple/Maddori.Apple/Network/Response/KeywordResponse.swift
  Maddori.Apple/Maddori.Apple/Network/Response/MemberResponse.swift
  Maddori.Apple/Maddori.Apple/Network/Response/ReflectionInfoResponse.swift
  Maddori.Apple/Maddori.Apple/Network/Response/ReflectionResponse.swift
Labels: ✨ Feature

#107 [CHORE] Alamofire 추가
  Maddori.Apple/Maddori.Apple.xcodeproj/project.pbxproj
  Maddori.Apple/Maddori.Apple.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: 🙏 ASAP

#109 [FEAT] Setup View들 API연결 완료
  Maddori.Apple/Maddori.Apple.xcodeproj/project.pbxproj
  Maddori.Apple/Maddori.Apple/Global/Base/BaseTextFieldViewController.swift
  Maddori.Apple/Maddori.Apple/Global/Literal/UrlLiteral.swift
  Maddori.Apple/Maddori.Apple/Global/Supports/SceneDelegate.swift
  Maddori.Apple/Maddori.Apple/Network/EndPoint/SetupEndPoint.swift
  Maddori.Apple/Maddori.Apple/Network/Storage/UserDefaultHandler.swift
  Maddori.Apple/Maddori.Apple/Network/Storage/UserDefaultStorage.swift
  Maddori.Apple/Maddori.Apple/Screen/Setup/CreateTeam/CreateTeamViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/Setup/JoinTeam/JoinTeamViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/Setup/Login/LoginViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/Setup/SetNickname/SetNicknameViewController.swift
Labels: ✨ Feature, 🙏 ASAP

#112 [CHORE] API 수정에 따른 모델 수정
  Maddori.Apple/Maddori.Apple.xcodeproj/project.pbxproj
  Maddori.Apple/Maddori.Apple/Network/Response/AddReflectionResponse.swift
  Maddori.Apple/Maddori.Apple/Network/Response/AllCertainTypeFeedBackResponse.swift
  Maddori.Apple/Maddori.Apple/Network/Response/AllFeedBackResponse.swift
  Maddori.Apple/Maddori.Apple/Network/Response/AllReflectionResponse.swift
  Maddori.Apple/Maddori.Apple/Network/Response/CertainTeamDetailResponse.swift
  Maddori.Apple/Maddori.Apple/Network/Response/CreateTeamResponse.swift
  Maddori.Apple/Maddori.Apple/Network/Response/CurrentMemberResponse.swift
  Maddori.Apple/Maddori.Apple/Network/Response/CurrentReflectionResponse.swift
  Maddori.Apple/Maddori.Apple/Network/Response/EditFeedBackResponse.swift
  Maddori.Apple/Maddori.Apple/Network/Response/FeedBackContentResponse.swift
  Maddori.Apple/Maddori.Apple/Network/Response/FeedBackInfoResponse.swift
  Maddori.Apple/Maddori.Apple/Network/Response/FeedBackResponse.swift
  Maddori.Apple/Maddori.Apple/Network/Response/JoinTeamResponse.swift
  Maddori.Apple/Maddori.Apple/Network/Response/KeywordResponse.swift
  Maddori.Apple/Maddori.Apple/Network/Response/MemberResponse.swift
  Maddori.Apple/Maddori.Apple/Network/Response/ReflectionInfoResponse.swift
  Maddori.Apple/Maddori.Apple/Network/Response/ReflectionResponse.swift
  Maddori.Apple/Maddori.Apple/Network/Response/TeamInfoResponse.swift
Labels: ✨ Feature, 🙏 ASAP

#114 [FEAT] 방 참가하기 api 연결
  Maddori.Apple/Maddori.Apple.xcodeproj/project.pbxproj
  Maddori.Apple/Maddori.Apple/Global/Extension/UIViewController+Extension.swift
  Maddori.Apple/Maddori.Apple/Global/UIComponent/View/AlertViewController.swift
  Maddori.Apple/Maddori.Apple/Network/EndPoint/SetupEndPoint.swift
  Maddori.Apple/Maddori.Apple/Network/Reqeust/DTO/CertainTeamDTO.swift
  Maddori.Apple/Maddori.Apple/Network/Storage/UserDefaultHandler.swift
  Maddori.Apple/Maddori.Apple/Network/Storage/UserDefaultStorage.swift
  Maddori.Apple/Maddori.Apple/Screen/Setup/CreateTeam/CreateTeamViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/Setup/InvitationCode/InvitationCodeViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/Setup/JoinTeam/JoinTeamViewController.swift
Labels: ✨ Feature, 🙏 ASAP

#124 [FEAT] 나의 회고 탭 관련 API 연결
  Maddori.Apple/Maddori.Apple.xcodeproj/project.pbxproj
  Maddori.Apple/Maddori.Apple/Network/EndPoint/MyReflectionEndPoint.swift
  Maddori.Apple/Maddori.Apple/Network/Reqeust/DTO/EncodeDTO.swift
  Maddori.Apple/Maddori.Apple/Screen/MyReflection/MyReflection/MyReflectionViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/MyReflection/MyReflectionDetail/MyReflectionDetailViewController.swift
Labels: ✨ Feature

#120 [FEAT] 보관함 탭 데이터 API 연결
  Maddori.Apple/Maddori.Apple.xcodeproj/project.pbxproj
  Maddori.Apple/Maddori.Apple/Network/EndPoint/MyFeedBackEndPoint.swift
  Maddori.Apple/Maddori.Apple/Screen/MyFeedback/MyFeedback/MyFeedbackViewController.swift
Labels: ✨ Feature, 🙏 ASAP, 📡 API

#118 [FEAT] 피드백 추가하기 API 연결
  Maddori.Apple/Maddori.Apple.xcodeproj/project.pbxproj
  Maddori.Apple/Maddori.Apple/Global/UIComponent/CollectionView/MemberCollectionView/MemberCollectionView.swift
  Maddori.Apple/Maddori.Apple/Global/UIComponent/CollectionView/MemberCollectionView/MemberCollectionViewCell.swift
  Maddori.Apple/Maddori.Apple/Network/EndPoint/AddFeedBackEndPoint.swift
  Maddori.Apple/Maddori.Apple/Network/Reqeust/DTO/FeedBackContentDTO.swift
  Maddori.Apple/Maddori.Apple/Network/Response/MemberResponse.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/AddFeedback/AddFeedbackViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/SelectFeedbackMember/SelectFeedbackMemberViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/SelectReflectionMember/SelectReflectionMemberViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/MyFeedback/MyFeedbackDetail/MyFeedbackDetailViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/Setup/SetNickname/SetNicknameViewController.swift
Labels: ✨ Feature, 🙏 ASAP, 📡 API

#123 [FEAT] 특정 피드백 삭제, 수정하기 API 구현
  Maddori.Apple/Maddori.Apple.xcodeproj/project.pbxproj
  Maddori.Apple/Maddori.Apple/Global/UIComponent/View/AlertViewController.swift
  Maddori.Apple/Maddori.Apple/Network/EndPoint/MyFeedBackEndPoint.swift
  Maddori.Apple/Maddori.Apple/Network/Model/VoidModel.swift
  Maddori.Apple/Maddori.Apple/Network/Reqeust/DTO/EditFeedBackDTO.swift
  Maddori.Apple/Maddori.Apple/Screen/MyFeedback/MyFeedback/MyFeedbackViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/MyFeedback/MyFeedbackEdit/MyFeedbackEditViewController.swift
Labels: ✨ Feature, 🙏 ASAP, 📡 API

#129 [FIX] 닉네임 설정 api request를 팀 합류 api request할 때 같이 전달하기
  Maddori.Apple/Maddori.Apple.xcodeproj/xcshareddata/xcschemes/Maddori.Apple.xcscheme
  Maddori.Apple/Maddori.Apple/Global/UIComponent/View/AlertViewController.swift
  Maddori.Apple/Maddori.Apple/Network/Response/MemberResponse.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/SelectFeedbackMember/SelectFeedbackMemberViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/Setup/CreateTeam/CreateTeamViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/Setup/SetNickname/SetNicknameViewController.swift
Labels: 🐞 Bugfix, 🙏 ASAP

#132 [CHORE] DB에서 테스트하기 위해 초반 flow를 다듬었습니다.
  Maddori.Apple/Maddori.Apple/Global/UIComponent/View/AlertViewController.swift
  Maddori.Apple/Maddori.Apple/Network/EndPoint/HomeEndPoint.swift
  Maddori.Apple/Maddori.Apple/Network/EndPoint/SetupEndPoint.swift
  Maddori.Apple/Maddori.Apple/Network/Response/JoinTeamResponse.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/Home/HomeViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/Setup/CreateTeam/CreateTeamViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/Setup/InvitationCode/InvitationCodeViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/Setup/JoinTeam/JoinTeamViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/Setup/SetNickname/SetNicknameViewController.swift
Labels: ✨ Feature, 🙏 ASAP, 📡 API

#135 [FEAT] 현재 팀, 현재 회고의 피드백 추가하기 기능 추가
  Maddori.Apple/Maddori.Apple/Global/UIComponent/CollectionView/MemberCollectionView/MemberCollectionView.swift
  Maddori.Apple/Maddori.Apple/Global/UIComponent/View/AlertViewController.swift
  Maddori.Apple/Maddori.Apple/Network/EndPoint/AddFeedBackEndPoint.swift
  Maddori.Apple/Maddori.Apple/Network/EndPoint/HomeEndPoint.swift
  Maddori.Apple/Maddori.Apple/Network/Response/MemberResponse.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/AddFeedback/AddFeedbackViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/Home/HomeViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/SelectFeedbackMember/SelectFeedbackMemberViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/MyFeedback/MyFeedbackDetail/MyFeedbackDetailViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/Setup/CreateTeam/CreateTeamViewController.swift
Labels: ✨ Feature, 🙏 ASAP, 📡 API

#142 [CHORE] HomeView isAdmin 인지에 따라 분기처리 완료
  Maddori.Apple/Maddori.Apple/Screen/Home/Home/HomeViewController.swift
Labels: 🛠 Chore

#137 [FEAT] 보관함 탭 API + View 연결
  Maddori.Apple/Maddori.Apple/Network/EndPoint/MyFeedBackEndPoint.swift
  Maddori.Apple/Maddori.Apple/Screen/MyFeedback/MyFeedback/MyFeedbackViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/MyFeedback/MyFeedback/UIComponent/MyFeedbackCollectionView.swift
Labels: ✨ Feature, 📡 API

#140 [FEAT] updateReflectionDetail API 연결 및 view 적용
  Maddori.Apple/Maddori.Apple.xcodeproj/project.pbxproj
  Maddori.Apple/Maddori.Apple/Global/Extension/String+Extension.swift
  Maddori.Apple/Maddori.Apple/Network/EndPoint/CreateReflectionEndPoint.swift
  Maddori.Apple/Maddori.Apple/Network/Response/AddReflectionResponse.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/CreateReflection/CreateReflectionViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/CreateReflection/UIComponent/ReflectionNameView.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/Home/HomeViewController.swift
Labels: ✨ Feature, 📡 API

#150 [FEAT] 나의 회고 API 연결 후 데이터 올리기까지 완료
  Maddori.Apple/Maddori.Apple/Network/Response/AllReflectionResponse.swift
  Maddori.Apple/Maddori.Apple/Screen/MyReflection/MyReflection/MyReflectionViewController.swift
Labels: 📡 API

#153 [FEAT] 나의회고 디테일 뷰 API 연결
  Maddori.Apple/Maddori.Apple/Network/EndPoint/MyReflectionEndPoint.swift
  Maddori.Apple/Maddori.Apple/Screen/MyReflection/MyReflection/MyReflectionViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/MyReflection/MyReflectionDetail/Cell/MyReflectionDetailTableViewCell.swift
  Maddori.Apple/Maddori.Apple/Screen/MyReflection/MyReflectionDetail/MyReflectionDetailViewController.swift
Labels: 📡 API

#156 [FEAT] 나의회고 디테일 뷰 API에서 데이터 넘기기
  Maddori.Apple/Maddori.Apple/Screen/MyReflection/MyReflectionDetail/MyReflectionDetailViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/MyReflection/MyReflectionFeedback/MyReflectionFeedbackViewController.swift
Labels: 🏖 Relax

#149 [CHORE] 닉네임 3글자 넘어갈 시 ..으로 바꾸기
  Maddori.Apple/Maddori.Apple/Screen/MyFeedback/MyFeedback/Cell/MyFeedbackMemberCollectionViewCell.swift
Labels: 🛠 Chore

#144 [CHORE] HomeView invitationCode 복사 구현
  Maddori.Apple/Maddori.Apple/Screen/Home/Home/HomeViewController.swift
Labels: 🛠 Chore

#146 [CHORE] MyReflectionDetailView의 empty view 추가
  Maddori.Apple/Maddori.Apple/Global/Literal/TextLiteral.swift
  Maddori.Apple/Maddori.Apple/Global/UIComponent/View/EmptyView/EmptyFeedbackView.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/InProgress/InProgressViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/MyFeedback/MyFeedback/UIComponent/MyFeedbackCollectionView.swift
  Maddori.Apple/Maddori.Apple/Screen/MyReflection/MyReflectionDetail/MyReflectionDetailViewController.swift
Labels: 🛠 Chore

#138 [FEAT] InProgress API 연결 및 View 표시와 연결
  Maddori.Apple/Maddori.Apple.xcodeproj/project.pbxproj
  Maddori.Apple/Maddori.Apple/Global/UIComponent/CollectionView/KeywordCollectionView/KeywordCollectionViewCell.swift
  Maddori.Apple/Maddori.Apple/Global/UIComponent/CollectionView/KeywordCollectionView/KeywordCollectionViewFlowLayout.swift
  Maddori.Apple/Maddori.Apple/Global/UIComponent/CollectionView/MemberCollectionView/MemberCollectionView.swift
  Maddori.Apple/Maddori.Apple/Network/EndPoint/InProgressEndPoint.swift
  Maddori.Apple/Maddori.Apple/Network/Model/Keyword/Keyword.swift
  Maddori.Apple/Maddori.Apple/Network/Model/ReflectionInfo/ReflectionInfoModel.swift
  Maddori.Apple/Maddori.Apple/Network/Response/FeedBackContentResponse.swift
  Maddori.Apple/Maddori.Apple/Network/Response/ReflectionResponse.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/CreateReflection/CreateReflectionViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/Home/HomeViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/InProgress/InProgressViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/InProgressDetail/InProgressDetailViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/SelectReflectionMember/SelectReflectionMemberViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/StartReflection/StartReflectionViewController.swift
Labels: ✨ Feature, 👏 Improvement, 🙏 ASAP, 📡 API

#158 [CHORE] AddFeedback & MyFeedbackDetail & MyFeedbackEdit 레이아웃 수정
  Maddori.Apple/Maddori.Apple/Global/Literal/TextLiteral.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/AddFeedback/AddFeedbackViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/MyFeedback/MyFeedback/MyFeedbackViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/MyFeedback/MyFeedbackDetail/MyFeedbackDetailViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/MyFeedback/MyFeedbackEdit/MyFeedbackEditViewController.swift
Labels: 🐞 Bugfix, 🙏 ASAP

#157 [ADD] JoinReflectionButton UI 추가 및 버튼 추가
  Maddori.Apple/Maddori.Apple.xcodeproj/project.pbxproj
  Maddori.Apple/Maddori.Apple/Global/Extension/UIFont+Extension.swift
  Maddori.Apple/Maddori.Apple/Global/Literal/ImageLiteral.swift
  Maddori.Apple/Maddori.Apple/Global/Literal/TextLiteral.swift
  Maddori.Apple/Maddori.Apple/Global/Resource/Assets.xcassets/YellowCalendar.imageset/Contents.json
  Maddori.Apple/Maddori.Apple/Global/Resource/Assets.xcassets/YellowCalendar.imageset/yellowCalendar.pdf
  Maddori.Apple/Maddori.Apple/Global/UIComponent/CollectionView/KeywordCollectionView/KeywordCollectionViewFlowLayout.swift
  Maddori.Apple/Maddori.Apple/Network/Storage/UserDefaultHandler.swift
  Maddori.Apple/Maddori.Apple/Network/Storage/UserDefaultStorage.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/Home/HomeViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/Home/UIComponent/JoinReflectionButton.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/SelectReflectionMember/SelectReflectionMemberViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/StartReflection/StartReflectionViewController.swift
Labels: ✨ Feature, 🙏 ASAP

#164 [CHORE] MyReflectionDetail의 Cell에 이름 lable 사이즈 재조정
  Maddori.Apple/Maddori.Apple/Screen/MyReflection/MyReflectionDetail/Cell/MyReflectionDetailTableViewCell.swift
Labels: 🛠 Chore

#159 [FEAT] 피드백 보관함 수정 삭제 기능 완료
  Maddori.Apple/Maddori.Apple/Global/Extension/UIViewController+Extension.swift
  Maddori.Apple/Maddori.Apple/Global/UIComponent/View/AlertViewController.swift
  Maddori.Apple/Maddori.Apple/Network/EndPoint/MyFeedBackEndPoint.swift
  Maddori.Apple/Maddori.Apple/Network/Model/FeedbackFromMe/FeedbackFromMeModel.swift
  Maddori.Apple/Maddori.Apple/Network/Reqeust/DTO/EditFeedBackDTO.swift
  Maddori.Apple/Maddori.Apple/Network/Response/KeywordResponse.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/AddFeedback/AddFeedbackViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/MyFeedback/MyFeedback/MyFeedbackViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/MyFeedback/MyFeedback/UIComponent/MyFeedbackCollectionView.swift
  Maddori.Apple/Maddori.Apple/Screen/MyFeedback/MyFeedbackDetail/MyFeedbackDetailViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/MyFeedback/MyFeedbackEdit/MyFeedbackEditViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/Setup/JoinTeam/JoinTeamViewController.swift
Labels: ✨ Feature, 🙏 ASAP, 📡 API

#162 [FEAT] Apple Login 기능 추가
  Maddori.Apple/Maddori.Apple.xcodeproj/project.pbxproj
  Maddori.Apple/Maddori.Apple/Maddori.Apple.entitlements
  Maddori.Apple/Maddori.Apple/Network/EndPoint/SetupEndPoint.swift
  Maddori.Apple/Maddori.Apple/Network/Reqeust/DTO/AppleLoginDTO.swift
  Maddori.Apple/Maddori.Apple/Network/Response/AppleLoginResponse.swift
  Maddori.Apple/Maddori.Apple/Network/Response/UserResponse.swift
  Maddori.Apple/Maddori.Apple/Network/Storage/UserDefaultHandler.swift
  Maddori.Apple/Maddori.Apple/Network/Storage/UserDefaultStorage.swift
  Maddori.Apple/Maddori.Apple/Screen/Setup/Login/LoginViewController.swift
Labels: ✨ Feature, 🙏 ASAP, 📡 API

#127 [CHORE] Endpointable Protocol 추가
  Maddori.Apple/Maddori.Apple.xcodeproj/project.pbxproj
  Maddori.Apple/Maddori.Apple/Network/EndPoint/HomeEndPoint.swift
  Maddori.Apple/Maddori.Apple/Network/EndPoint/InProgressEndPoint.swift
  Maddori.Apple/Maddori.Apple/Network/EndPoint/MyReflectionEndPoint.swift
  Maddori.Apple/Maddori.Apple/Network/EndPoint/SetupEndPoint.swift
  Maddori.Apple/Maddori.Apple/Network/Protocol/Endpointable.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/Home/HomeViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/InProgress/InProgressViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/SelectReflectionMember/SelectReflectionMemberViewController.swift
Labels: ✨ Feature, 🏖 Relax, 📡 API

#168 [FIX] 보관함 탭 멤버 리스트 쌓이는 문제 해결
  Maddori.Apple/Maddori.Apple/Screen/MyFeedback/MyFeedback/MyFeedbackViewController.swift
Labels: 🐞 Bugfix, 🙏 ASAP

#166 [FEAT] 로그아웃 구현
  Maddori.Apple/Maddori.Apple.xcodeproj/project.pbxproj
  Maddori.Apple/Maddori.Apple/Global/Literal/ImageLiteral.swift
  Maddori.Apple/Maddori.Apple/Global/Supports/SceneDelegate.swift
  Maddori.Apple/Maddori.Apple/Global/UIComponent/Button/LogOutButton.swift
  Maddori.Apple/Maddori.Apple/Screen/MyReflection/MyReflection/MyReflectionViewController.swift
Labels: 🙏 ASAP

#173 [FIX] 자잘자잘한 버그 수정하기
  Maddori.Apple/Maddori.Apple/Global/Literal/TextLiteral.swift
  Maddori.Apple/Maddori.Apple/Global/UIComponent/View/LabelButtonView.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/SelectReflectionMember/SelectReflectionMemberViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/Setup/CreateTeam/CreateTeamViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/Setup/InvitationCode/InvitationCodeViewController.swift
Labels: 🐞 Bugfix

#176 [FIX] 회고 일정 보여주는 포맷 수정하기
  Maddori.Apple/Maddori.Apple.xcodeproj/project.pbxproj
  Maddori.Apple/Maddori.Apple/Global/Extension/Date+Extension.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/Home/HomeViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/MyReflection/MyReflection/MyReflectionViewController.swift
Labels: 🐞 Bugfix

#177 [FIX] 키보드 올라왔을때 버튼이 올라오지 않는 문제 수정
  Maddori.Apple/Maddori.Apple/Global/Base/BaseTextFieldViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/Setup/SetNickname/SetNicknameViewController.swift
Labels: 🐞 Bugfix

#178 [FIX] 피드백 수정에서 start 토글 반영안되는 문제 해결
  Maddori.Apple/Maddori.Apple/Network/Response/MemberResponse.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/AddFeedback/AddFeedbackViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/MyFeedback/MyFeedbackDetail/MyFeedbackDetailViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/MyFeedback/MyFeedbackEdit/MyFeedbackEditViewController.swift
Labels: 🐞 Bugfix, 🙏 ASAP

#180 [FIX] Start Content Post 로직 수정하기
  Maddori.Apple/Maddori.Apple/Screen/Home/AddFeedback/AddFeedbackViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/MyFeedback/MyFeedbackEdit/MyFeedbackEditViewController.swift
Labels: 🙏 ASAP

#181 [CHORE] v1.2 앱 심사 제출
  Maddori.Apple/Maddori.Apple.xcodeproj/project.pbxproj
  Maddori.Apple/Maddori.Apple/Global/Literal/TextLiteral.swift
  Maddori.Apple/Maddori.Apple/Network/Model/Member/Member.swift
  Maddori.Apple/Maddori.Apple/Network/Response/UserResponse.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/AddFeedback/AddFeedbackViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/MyFeedback/MyFeedback/MyFeedbackViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/MyFeedback/MyFeedbackDetail/MyFeedbackDetailViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/MyFeedback/MyFeedbackEdit/MyFeedbackEditViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/MyReflection/MyReflectionDetail/Cell/MyReflectionDetailTableViewCell.swift
  Maddori.Apple/Maddori.Apple/Screen/MyReflection/MyReflectionDetail/MyReflectionDetailViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/MyReflection/MyReflectionFeedback/MyReflectionFeedbackViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/Setup/CreateTeam/CreateTeamViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/Setup/InvitationCode/InvitationCodeViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/Setup/Login/LoginViewController.swift
Labels: 📱 QA

#185 [FIX] 나의 회고 디테일에 세그먼트가 겹치는 문제 해결
  Maddori.Apple/Maddori.Apple.xcodeproj/project.pbxproj
  Maddori.Apple/Maddori.Apple/Screen/MyReflection/MyReflectionDetail/Cell/MyReflectionDetailViewLastCell.swift
  Maddori.Apple/Maddori.Apple/Screen/MyReflection/MyReflectionDetail/MyReflectionDetailViewController.swift
Labels: 🐞 Bugfix, 🙏 ASAP

#186 [FEAT] 회원탈퇴 기능 추가
  Maddori.Apple/Maddori.Apple.xcodeproj/project.pbxproj
  Maddori.Apple/Maddori.Apple/Global/Literal/ImageLiteral.swift
  Maddori.Apple/Maddori.Apple/Global/Literal/TextLiteral.swift
  Maddori.Apple/Maddori.Apple/Global/UIComponent/Button/SettingButton.swift
  Maddori.Apple/Maddori.Apple/Network/EndPoint/MyReflectionEndPoint.swift
  Maddori.Apple/Maddori.Apple/Screen/MyReflection/MyReflection/MyReflectionViewController.swift
Labels: ✨ Feature, 🙏 ASAP

#190 [CHORE] 회고가 진행중으로 넘어갔을 때, 피드백 수정 삭제 불가능하도록 분기처리
  Maddori.Apple/Maddori.Apple/Global/Literal/TextLiteral.swift
  Maddori.Apple/Maddori.Apple/Network/Model/FeedbackFromMe/FeedbackFromMeModel.swift
  Maddori.Apple/Maddori.Apple/Screen/MyFeedback/MyFeedback/MyFeedbackViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/MyFeedback/MyFeedback/UIComponent/MyFeedbackCollectionView.swift
  Maddori.Apple/Maddori.Apple/Screen/MyFeedback/MyFeedbackDetail/MyFeedbackDetailViewController.swift
Labels: 🛠 Chore

#193 [CHORE] 탈퇴한 멤버에게 받은 피드백 정보 안뜨는 문제 해결
  Maddori.Apple/Maddori.Apple/Global/Literal/TextLiteral.swift
  Maddori.Apple/Maddori.Apple/Screen/MyReflection/MyReflection/MyReflectionViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/MyReflection/MyReflectionDetail/MyReflectionDetailViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/MyReflection/MyReflectionFeedback/MyReflectionFeedbackViewController.swift
Labels: 🛠 Chore
