Repository DeveloperAcademy-POSTECH/MacC-Team-Maddori.Apple, pull requests merged in 2022-12, with the labels that each got.

#195 [FIX] 회고 디테일 뷰 API 분리
  Maddori.Apple/Maddori.Apple/Screen/MyReflection/MyReflectionDetail/MyReflectionDetailViewController.swift
Labels: 🐞 Bugfix

#196 [CHORE] 회고 일정 추가 후 dismiss되게 변경
  Maddori.Apple/Maddori.Apple/Screen/Home/CreateReflection/CreateReflectionViewController.swift
Labels: 🛠 Chore

#198 [FIX] 초대코드 복사 토스트가 계속 내려오는 문제 해결
  Maddori.Apple/Maddori.Apple/Screen/Setup/InvitationCode/InvitationCodeViewController.swift
Labels: 🐞 Bugfix

#201 [CHORE] 디테일 상세보기 화면에서 스크롤 안되는 문제 해결
  Maddori.Apple/Maddori.Apple/Screen/Home/InProgress/InProgressViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/InProgressDetail/InProgressDetailViewController.swift
Labels: 🛠 Chore

#204 [CHORE] 리더가 회고를 종료하더라도 Home 화면에 반영되지 않는 문제 해결
  Maddori.Apple/Maddori.Apple/Global/UIComponent/CollectionView/MemberCollectionView/MemberCollectionView.swift
  Maddori.Apple/Maddori.Apple/Network/Response/CertainTeamDetailResponse.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/CreateReflection/CreateReflectionViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/CreateReflection/UIComponent/ReflectionNameView.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/Home/HomeViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/SelectReflectionMember/SelectReflectionMemberViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/StartReflection/StartReflectionViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/MyFeedback/MyFeedbackDetail/MyFeedbackDetailViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/Setup/CreateTeam/CreateTeamViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/Setup/JoinTeam/JoinTeamViewController.swift
Labels: 🙏 ASAP, 🛠 Chore

#208 v1.2.3 출시에 따른 develop branch 업데이트
  Maddori.Apple/Maddori.Apple.xcodeproj/project.pbxproj
  Maddori.Apple/Maddori.Apple/Screen/Home/Home/HomeViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/SelectReflectionMember/SelectReflectionMemberViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/StartReflection/StartReflectionViewController.swift
Labels: 🛠 Chore

#211 [ADD] 새로 만든 addFeedback view에서 2, 3, 4단계 구현
  Maddori.Apple/Maddori.Apple.xcodeproj/project.pbxproj
  Maddori.Apple/Maddori.Apple/Global/Extension/UIFont+Extension.swift
  Maddori.Apple/Maddori.Apple/Global/Literal/ImageLiteral.swift
  Maddori.Apple/Maddori.Apple/Global/Literal/TextLiteral.swift
  Maddori.Apple/Maddori.Apple/Global/Resource/Assets.xcassets/ProgressBar2.imageset/Contents.json
  Maddori.Apple/Maddori.Apple/Global/Resource/Assets.xcassets/ProgressBar2.imageset/ProgressBar2.pdf
  Maddori.Apple/Maddori.Apple/Global/Resource/Assets.xcassets/ProgressBar3.imageset/Contents.json
  Maddori.Apple/Maddori.Apple/Global/Resource/Assets.xcassets/ProgressBar3.imageset/ProgressBar3.pdf
  Maddori.Apple/Maddori.Apple/Global/Resource/Assets.xcassets/ProgressBar4.imageset/Contents.json
  Maddori.Apple/Maddori.Apple/Global/Resource/Assets.xcassets/ProgressBar4.imageset/ProgressBar4.pdf
  Maddori.Apple/Maddori.Apple/Global/Resource/Assets.xcassets/ProgressBar5.imageset/Contents.json
  Maddori.Apple/Maddori.Apple/Global/Resource/Assets.xcassets/ProgressBar5.imageset/ProgressBar5.pdf
  Maddori.Apple/Maddori.Apple/Global/Resource/Assets.xcassets/ProgressBarEmpty.imageset/Contents.json
  Maddori.Apple/Maddori.Apple/Global/Resource/Assets.xcassets/ProgressBarEmpty.imageset/ProgressBarEmpty.pdf
  Maddori.Apple/Maddori.Apple/Screen/Home/AddFeedback/AddFeedbackContentViewController.swift
Labels: ✨ Feature

#216 [ADD] Feedback 선택 UI 변경
  Maddori.Apple/Maddori.Apple.xcodeproj/project.pbxproj
  Maddori.Apple/Maddori.Apple/Global/Literal/TextLiteral.swift
  Maddori.Apple/Maddori.Apple/Global/UIComponent/Button/FeedbackTypeButtonView.swift
  Maddori.Apple/Maddori.Apple/Global/UIComponent/View/FeedbackTypeButtonView.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/AddFeedback/AddFeedbackViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/MyFeedback/MyFeedbackEdit/MyFeedbackEditViewController.swift
Labels: ✨ Feature

#219 [ADD] 내가 쓴 피드백 상세 보기 화면에서의 키워드 UI를 변경했습니다.
  Maddori.Apple/Maddori.Apple.xcodeproj/project.pbxproj
  Maddori.Apple/Maddori.Apple/Global/UIComponent/View/KeywordView.swift
  Maddori.Apple/Maddori.Apple/Screen/MyFeedback/MyFeedbackDetail/MyFeedbackDetailViewController.swift
Labels: ✨ Feature

#226 [CHORE] 피드백 돌아보기 view에서 start 내용 삭제
  Maddori.Apple/Maddori.Apple/Screen/MyReflection/MyReflectionFeedback/MyReflectionFeedbackViewController.swift
Labels: 🛠 Chore

#218 [ADD] 새로 만든 AddFeedbackVC 에서 5번째 단계 구현
  Maddori.Apple/Maddori.Apple.xcodeproj/project.pbxproj
  Maddori.Apple/Maddori.Apple/Global/Extension/UIColor+Extension.swift
  Maddori.Apple/Maddori.Apple/Global/Extension/UIFont+Extension.swift
  Maddori.Apple/Maddori.Apple/Global/Literal/ImageLiteral.swift
  Maddori.Apple/Maddori.Apple/Global/Literal/TextLiteral.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/AddFeedback/AddFeedbackContentViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/AddFeedback/AddFeedbackKeywordViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/AddFeedback/UIComponent/KeywordTextField.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/SelectFeedbackMember/SelectFeedbackMemberViewController.swift
Labels: ✨ Feature

#224 [CHORE] 회고 중 homeview cell 터치 시 selectFeedbackMemberVC
  Maddori.Apple/Maddori.Apple/Screen/Home/Home/HomeViewController.swift
Labels: 🛠 Chore

#229 [ADD] 피드백 수정하기 UI변경에 따라 상속 삭제
  Maddori.Apple/Maddori.Apple.xcodeproj/project.pbxproj
  Maddori.Apple/Maddori.Apple/Global/UIComponent/View/FeedbackTypeButtonView.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/AddFeedback/AddFeedbackKeywordViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/AddFeedback/UIComponent/KeywordTextFieldView.swift
  Maddori.Apple/Maddori.Apple/Screen/MyFeedback/MyFeedbackDetail/MyFeedbackDetailViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/MyFeedback/MyFeedbackEdit/MyFeedbackEditViewController.swift
Labels: ✨ Feature, 👏 Improvement, 🙏 ASAP

#230 [ADD] 피드백 줄 멤버 선택, 타입 선택 뷰 구현
  Maddori.Apple/Maddori.Apple.xcodeproj/project.pbxproj
  Maddori.Apple/Maddori.Apple/Global/Literal/ImageLiteral.swift
  Maddori.Apple/Maddori.Apple/Global/Literal/TextLiteral.swift
  Maddori.Apple/Maddori.Apple/Global/Resource/Assets.xcassets/ProgressBar1.imageset/Contents.json
  Maddori.Apple/Maddori.Apple/Global/Resource/Assets.xcassets/ProgressBar1.imageset/Progress1.svg
  Maddori.Apple/Maddori.Apple/Global/UIComponent/CollectionView/MemberCollectionView/MemberCollectionView.swift
  Maddori.Apple/Maddori.Apple/Global/UIComponent/CollectionView/MemberCollectionView/MemberCollectionViewCell.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/Home/AddDetailFeedback/AddDetailFeedbackViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/Home/AddDetailFeedback/Model/FeedbackContent.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/Home/AddDetailFeedback/UIComponent/SelectKeywordTypeView.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/Home/AddDetailFeedback/UIComponent/SelectMemberView.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/Home/HomeViewController.swift
Labels: 👏 Improvement, 🙏 ASAP

#232 [FEAT] 피드백 상세히 주기부분 뷰 연결, 및 모델로 관리하기
  Maddori.Apple/Maddori.Apple.xcodeproj/project.pbxproj
  Maddori.Apple/Maddori.Apple/Screen/Home/AddFeedback/AddFeedbackContentViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/AddFeedback/AddFeedbackKeywordViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/Home/AddDetailFeedback/AddDetailFeedbackViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/Home/AddDetailFeedback/Model/FeedbackContent.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/Home/AddDetailFeedback/UIComponent/SelectMemberView.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/Home/HomeViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/SelectFeedbackMember/SelectFeedbackMemberViewController.swift
Labels: 🙏 ASAP

#233 [CHORE] UX writing 변경
  Maddori.Apple/Maddori.Apple/Global/Literal/TextLiteral.swift
Labels: 🙏 ASAP, 🛠 Chore

#234 [CHORE] v1.3
  .github/workflows/build.yml
  Maddori.Apple/Maddori.Apple.xcodeproj/project.pbxproj
  Maddori.Apple/Maddori.Apple/Global/Extension/UIColor+Extension.swift
  Maddori.Apple/Maddori.Apple/Global/Extension/UIFont+Extension.swift
  Maddori.Apple/Maddori.Apple/Global/Literal/ImageLiteral.swift
  Maddori.Apple/Maddori.Apple/Global/Literal/TextLiteral.swift
  Maddori.Apple/Maddori.Apple/Global/Resource/Assets.xcassets/ProgressBar1.imageset/Contents.json
  Maddori.Apple/Maddori.Apple/Global/Resource/Assets.xcassets/ProgressBar1.imageset/Progress1.svg
  Maddori.Apple/Maddori.Apple/Global/Resource/Assets.xcassets/ProgressBar2.imageset/Contents.json
  Maddori.Apple/Maddori.Apple/Global/Resource/Assets.xcassets/ProgressBar2.imageset/ProgressBar2.pdf
  Maddori.Apple/Maddori.Apple/Global/Resource/Assets.xcassets/ProgressBar3.imageset/Contents.json
  Maddori.Apple/Maddori.Apple/Global/Resource/Assets.xcassets/ProgressBar3.imageset/ProgressBar3.pdf
  Maddori.Apple/Maddori.Apple/Global/Resource/Assets.xcassets/ProgressBar4.imageset/Contents.json
  Maddori.Apple/Maddori.Apple/Global/Resource/Assets.xcassets/ProgressBar4.imageset/ProgressBar4.pdf
  Maddori.Apple/Maddori.Apple/Global/Resource/Assets.xcassets/ProgressBar5.imageset/Contents.json
  Maddori.Apple/Maddori.Apple/Global/Resource/Assets.xcassets/ProgressBar5.imageset/ProgressBar5.pdf
  Maddori.Apple/Maddori.Apple/Global/Resource/Assets.xcassets/ProgressBarEmpty.imageset/Contents.json
  Maddori.Apple/Maddori.Apple/Global/Resource/Assets.xcassets/ProgressBarEmpty.imageset/ProgressBarEmpty.pdf
  Maddori.Apple/Maddori.Apple/Global/UIComponent/Button/FeedbackTypeButtonView.swift
  Maddori.Apple/Maddori.Apple/Global/UIComponent/CollectionView/MemberCollectionView/MemberCollectionView.swift
  Maddori.Apple/Maddori.Apple/Global/UIComponent/CollectionView/MemberCollectionView/MemberCollectionViewCell.swift
  Maddori.Apple/Maddori.Apple/Global/UIComponent/View/FeedbackTypeButtonView.swift
  Maddori.Apple/Maddori.Apple/Global/UIComponent/View/KeywordView.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/AddFeedback/AddFeedbackContentViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/AddFeedback/AddFeedbackKeywordViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/AddFeedback/AddFeedbackViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/AddFeedback/UIComponent/KeywordTextFieldView.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/Home/AddDetailFeedback/AddDetailFeedbackViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/Home/AddDetailFeedback/Model/FeedbackContent.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/Home/AddDetailFeedback/UIComponent/SelectKeywordTypeView.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/Home/AddDetailFeedback/UIComponent/SelectMemberView.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/Home/HomeViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/SelectFeedbackMember/SelectFeedbackMemberViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/MyFeedback/MyFeedbackDetail/MyFeedbackDetailViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/MyFeedback/MyFeedbackEdit/MyFeedbackEditViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/MyReflection/MyReflectionFeedback/MyReflectionFeedbackViewController.swift
  README.md
Labels: Main

#235 [CHORE] v1.3에 따른 develop 브랜치 업데이트
  Maddori.Apple/Maddori.Apple.xcodeproj/project.pbxproj
Labels: Main

#238 [ADD] 오픈소스 라이브러리 설정 앱에 추가
  Maddori.Apple/Maddori.Apple.xcodeproj/project.pbxproj
  Maddori.Apple/Settings.bundle/Root.plist
  Maddori.Apple/Settings.bundle/com.mono0926.LicensePlist.latest_result.txt
  Maddori.Apple/Settings.bundle/com.mono0926.LicensePlist.plist
  Maddori.Apple/Settings.bundle/com.mono0926.LicensePlist/Alamofire.plist
  Maddori.Apple/Settings.bundle/com.mono0926.LicensePlist/SnapKit.plist
  Maddori.Apple/Settings.bundle/en.lproj/Root.strings
Labels: ✨ Feature
