Repository DeveloperAcademy-POSTECH/MacC-Team-Maddori.Apple, pull requests merged in 2022-10, with the labels that each got.

#3 [SETTING] 초기 프로젝트 세팅과 메인버튼을 추가했습니다.
  Maddori.Apple/Maddori.Apple.xcodeproj/project.pbxproj
  Maddori.Apple/Maddori.Apple.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Maddori.Apple/Maddori.Apple/Base.lproj/Main.storyboard
  Maddori.Apple/Maddori.Apple/Global/Base/BaseCollectionViewCell.swift
  Maddori.Apple/Maddori.Apple/Global/Base/BaseTableViewCell.swift
  Maddori.Apple/Maddori.Apple/Global/Base/BaseViewController.swift
  Maddori.Apple/Maddori.Apple/Global/Extension/NSObject+Extension.swift
  Maddori.Apple/Maddori.Apple/Global/Extension/UIButton+Extension.swift
  Maddori.Apple/Maddori.Apple/Global/Extension/UIColor+Extension.swift
  Maddori.Apple/Maddori.Apple/Global/Extension/UIFont+Extension.swift
  Maddori.Apple/Maddori.Apple/Global/Extension/UIViewController+Extension.swift
  Maddori.Apple/Maddori.Apple/Global/Literal/ImageLiteral.swift
  Maddori.Apple/Maddori.Apple/Global/Literal/SizeLiteral.swift
  Maddori.Apple/Maddori.Apple/Global/Literal/TextLiteral.swift
  Maddori.Apple/Maddori.Apple/Global/Resource/Assets.xcassets/AccentColor.colorset/Contents.json
  Maddori.Apple/Maddori.Apple/Global/Resource/Assets.xcassets/AppIcon.appiconset/Contents.json
  Maddori.Apple/Maddori.Apple/Global/Resource/Assets.xcassets/Contents.json
  Maddori.Apple/Maddori.Apple/Global/Resource/Base.lproj/LaunchScreen.storyboard
  Maddori.Apple/Maddori.Apple/Global/Supports/AppDelegate.swift
  Maddori.Apple/Maddori.Apple/Global/Supports/Info.plist
  Maddori.Apple/Maddori.Apple/Global/Supports/SceneDelegate.swift
  Maddori.Apple/Maddori.Apple/Global/UIComponent/MainButton.swift
  Maddori.Apple/Maddori.Apple/Network/Model/Request/SampleDTO.swift
  Maddori.Apple/Maddori.Apple/Network/Model/Response/Sample.swift
  Maddori.Apple/Maddori.Apple/Screen/Main/MainViewController.swift
  Maddori.Apple/Maddori.Apple/ViewController.swift
Labels: 👏 Improvement, ⚙️ Setting

#9 [SETTING] iOS Deployment target 16 -> 14로 변경
  Maddori.Apple/Maddori.Apple.xcodeproj/project.pbxproj
Labels: 👏 Improvement, ⚙️ Setting

#10 [SETTING] 컬러에셋, 폰트 에셋 추가
  Maddori.Apple/Maddori.Apple.xcodeproj/project.pbxproj
  Maddori.Apple/Maddori.Apple/Global/Extension/UIColor+Extension.swift
  Maddori.Apple/Maddori.Apple/Global/Extension/UIFont+Extension.swift
  Maddori.Apple/Maddori.Apple/Global/Extension/UILabel+Extension.swift
  Maddori.Apple/Maddori.Apple/Global/Extension/UIViewController+Extension.swift
  Maddori.Apple/Maddori.Apple/Global/UIComponent/MainButton.swift
Labels: 🙏 ASAP

#14 [FEAT] 닉네임 생성 UI 구현
  Maddori.Apple/Maddori.Apple.xcodeproj/project.pbxproj
  Maddori.Apple/Maddori.Apple/Global/Base/BaseViewController.swift
  Maddori.Apple/Maddori.Apple/Global/Literal/SizeLiteral.swift
  Maddori.Apple/Maddori.Apple/Global/Literal/TextLiteral.swift
  Maddori.Apple/Maddori.Apple/Global/UIComponent/KigoTextField.swift
  Maddori.Apple/Maddori.Apple/Screen/Signup/SignupViewController.swift
Labels: ✨ Feature, 👏 Improvement, 🏖 Relax

#15 [ADD] 새로운 회고 추가하기 View 생성
  Maddori.Apple/Maddori.Apple.xcodeproj/project.pbxproj
  Maddori.Apple/Maddori.Apple/Global/Extension/UILabel+Extension.swift
  Maddori.Apple/Maddori.Apple/Global/Extension/UITextField+Extension.swift
  Maddori.Apple/Maddori.Apple/Global/Literal/ImageLiteral.swift
  Maddori.Apple/Maddori.Apple/Global/Literal/TextLiteral.swift
  Maddori.Apple/Maddori.Apple/Global/UIComponent/CloseButton.swift
  Maddori.Apple/Maddori.Apple/Screen/AddReflection/AddReflectionViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/AddReflection/UIComponent/ReflectionNameView.swift
  Maddori.Apple/Maddori.Apple/Screen/Main/MainViewController.swift
Labels: ✨ Feature, 👏 Improvement, 🏖 Relax

#18 [ADD] KeywordLabel 컴포넌트화 완료
  Maddori.Apple/Maddori.Apple.xcodeproj/project.pbxproj
  Maddori.Apple/Maddori.Apple/Global/UIComponent/KeywordLabel.swift
  Maddori.Apple/Maddori.Apple/Screen/View/HomeViewController.swift
Labels: ✨ Feature, 👏 Improvement

#24 [FEAT] 베이스텍스트필드뷰컨트롤러 생성
  Maddori.Apple/Maddori.Apple.xcodeproj/project.pbxproj
  Maddori.Apple/Maddori.Apple/Global/Base/BaseTextFieldViewController.swift
  Maddori.Apple/Maddori.Apple/Global/Literal/TextLiteral.swift
  Maddori.Apple/Maddori.Apple/Screen/Setup/SetupNicknameViewController.swift
Labels: ✨ Feature, 🙏 ASAP

#17 [ADD] 피드백 추가하기_멤버 선택 뷰 구현
  Maddori.Apple/Maddori.Apple.xcodeproj/project.pbxproj
  Maddori.Apple/Maddori.Apple/Global/Extension/UILabel+Extension.swift
  Maddori.Apple/Maddori.Apple/Global/Literal/ImageLiteral.swift
  Maddori.Apple/Maddori.Apple/Global/Literal/TextLiteral.swift
  Maddori.Apple/Maddori.Apple/Global/UIComponent/ExitButton.swift
  Maddori.Apple/Maddori.Apple/Global/UIComponent/MemberCollectionView.swift
  Maddori.Apple/Maddori.Apple/Global/UIComponent/MemberCollectionViewCell.swift
  Maddori.Apple/Maddori.Apple/Screen/AddFeedbackMember/AddFeedbackMemberViewController.swift
Labels: ✨ Feature, 👏 Improvement

#31 [ADD] keywordCollectionView 레이아웃 완성 (feature/8-keyword-layout-sub 브랜치와 같은 PR(코드리뷰 반영함))
  Maddori.Apple/Maddori.Apple.xcodeproj/project.pbxproj
  Maddori.Apple/Maddori.Apple/Global/Literal/SizeLiteral.swift
  Maddori.Apple/Maddori.Apple/Global/UIComponent/KeywordLabel.swift
  Maddori.Apple/Maddori.Apple/Network/Model/Response/Keyword/Keyword.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/HomeViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/UIComponent/KeywordCollectionViewCell.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/UIComponent/KeywordCollectionViewFlowLayout.swift
  Maddori.Apple/Maddori.Apple/Screen/View/HomeViewController.swift
Labels: ✨ Feature, 👏 Improvement

#32 [FEAT] 팀 합류하기 UI 구현
  Maddori.Apple/Maddori.Apple.xcodeproj/project.pbxproj
  Maddori.Apple/Maddori.Apple/Global/Base/BaseTextFieldViewController.swift
  Maddori.Apple/Maddori.Apple/Global/Literal/SizeLiteral.swift
  Maddori.Apple/Maddori.Apple/Global/Literal/TextLiteral.swift
  Maddori.Apple/Maddori.Apple/Global/UIComponent/LabelButtonView.swift
  Maddori.Apple/Maddori.Apple/Screen/Setup/JoinTeamViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/Setup/SetupNicknameViewController.swift
Labels: ✨ Feature

#34 [CHORE] 코드 스타일 통일
  Maddori.Apple/Maddori.Apple.xcodeproj/project.pbxproj
  Maddori.Apple/Maddori.Apple/Global/Base/BaseCollectionViewCell.swift
  Maddori.Apple/Maddori.Apple/Global/Base/BaseTableViewCell.swift
  Maddori.Apple/Maddori.Apple/Global/Base/BaseTextFieldViewController.swift
  Maddori.Apple/Maddori.Apple/Global/Base/BaseViewController.swift
  Maddori.Apple/Maddori.Apple/Global/Extension/UIView+Extension.swift
  Maddori.Apple/Maddori.Apple/Global/Extension/UIViewController+Extension.swift
  Maddori.Apple/Maddori.Apple/Global/UIComponent/BackButton.swift
  Maddori.Apple/Maddori.Apple/Global/UIComponent/CloseButton.swift
  Maddori.Apple/Maddori.Apple/Global/UIComponent/KigoTextField.swift
  Maddori.Apple/Maddori.Apple/Global/UIComponent/MainButton.swift
  Maddori.Apple/Maddori.Apple/Global/UIComponent/MemberCollectionView.swift
  Maddori.Apple/Maddori.Apple/Global/UIComponent/MemberCollectionViewCell.swift
  Maddori.Apple/Maddori.Apple/Screen/AddFeedbackContent/AddFeedbackContentViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/AddFeedbackMember/AddFeedbackMemberViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/AddReflection/UIComponent/ReflectionNameView.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/HomeViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/UIComponent/KeywordCollectionViewCell.swift
  Maddori.Apple/Maddori.Apple/Screen/Setup/SetupNicknameViewController.swift
Labels: 👏 Improvement, 🏖 Relax

#35 [FEAT] 팀생성 UI 구현
  Maddori.Apple/Maddori.Apple.xcodeproj/project.pbxproj
  Maddori.Apple/Maddori.Apple/Global/Base/BaseTextFieldViewController.swift
  Maddori.Apple/Maddori.Apple/Global/Literal/TextLiteral.swift
  Maddori.Apple/Maddori.Apple/Screen/Setup/CreateTeamViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/Setup/JoinTeamViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/Setup/SetupNicknameViewController.swift
Labels: ✨ Feature, 👏 Improvement

#36 [ADD] 메인 뷰 UI 완성
  Maddori.Apple/Maddori.Apple/Global/Extension/UIFont+Extension.swift
  Maddori.Apple/Maddori.Apple/Global/Literal/SizeLiteral.swift
  Maddori.Apple/Maddori.Apple/Global/Literal/TextLiteral.swift
  Maddori.Apple/Maddori.Apple/Global/UIComponent/KeywordLabel.swift
  Maddori.Apple/Maddori.Apple/Network/Model/Response/Keyword/Keyword.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/HomeViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/UIComponent/KeywordCollectionViewCell.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/UIComponent/KeywordCollectionViewFlowLayout.swift
Labels: ✨ Feature

#37 [ADD] 피드백 추가하기 - TextView 구현
  Maddori.Apple/Maddori.Apple.xcodeproj/project.pbxproj
  Maddori.Apple/Maddori.Apple/Global/Literal/SizeLiteral.swift
  Maddori.Apple/Maddori.Apple/Global/Literal/TextLiteral.swift
  Maddori.Apple/Maddori.Apple/Global/UIComponent/FeedbackTextView.swift
  Maddori.Apple/Maddori.Apple/Global/UIComponent/FeedbackTypeButtonView.swift
  Maddori.Apple/Maddori.Apple/Screen/AddFeedbackContent/AddFeedbackContentViewController.swift
Labels: ✨ Feature, 👏 Improvement

#47 [FEAT] Start 피드백 추가하기 구현
  Maddori.Apple/Maddori.Apple.xcodeproj/project.pbxproj
  Maddori.Apple/Maddori.Apple/Global/Extension/Date+Extension.swift
  Maddori.Apple/Maddori.Apple/Global/Literal/TextLiteral.swift
  Maddori.Apple/Maddori.Apple/Global/UIComponent/FeedbackTextView.swift
  Maddori.Apple/Maddori.Apple/Screen/AddFeedbackContent/AddFeedbackContentViewController.swift
Labels: ✨ Feature, 🙏 ASAP

#54 Testflight용 branch 생성합니다
  Maddori.Apple/Maddori.Apple.xcodeproj/project.pbxproj
  Maddori.Apple/Maddori.Apple/Global/Base/BaseViewController.swift
  Maddori.Apple/Maddori.Apple/Global/Extension/UIDevice+Extension.swift
  Maddori.Apple/Maddori.Apple/Global/Extension/UIViewController+Extension.swift
  Maddori.Apple/Maddori.Apple/Global/Literal/ImageLiteral.swift
  Maddori.Apple/Maddori.Apple/Global/Literal/TextLiteral.swift
  Maddori.Apple/Maddori.Apple/Global/Supports/SceneDelegate.swift
  Maddori.Apple/Maddori.Apple/Network/Model/Response/Keyword/Keyword.swift
  Maddori.Apple/Maddori.Apple/Screen/AddFeedbackContent/AddFeedbackContentViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/FromTo/FromToViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/HomeViewController.swift
Labels: 🙏 ASAP

#52 [FEAT] TestFlight용 키워드 tap 작업
  Maddori.Apple/Maddori.Apple.xcodeproj/project.pbxproj
  Maddori.Apple/Maddori.Apple/Global/Extension/UIDevice+Extension.swift
  Maddori.Apple/Maddori.Apple/Global/Literal/ImageLiteral.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/HomeViewController.swift
Labels: ✨ Feature, 🧪 experiment

#55 [FEAT] 28일 할로윈파티 testFlight를 위한 앱으로 구현했습니다.
  Maddori.Apple/Maddori.Apple.xcodeproj/project.pbxproj
  Maddori.Apple/Maddori.Apple/Global/Extension/Encodable+Extension.swift
  Maddori.Apple/Maddori.Apple/Global/Literal/TextLiteral.swift
  Maddori.Apple/Maddori.Apple/Global/Resource/Assets.xcassets/AppIcon.appiconset/Contents.json
  Maddori.Apple/Maddori.Apple/Global/Resource/Assets.xcassets/AppIcon.appiconset/keygoAppIcon.png
  Maddori.Apple/Maddori.Apple/Global/UIComponent/FeedbackTypeButtonView.swift
  Maddori.Apple/Maddori.Apple/Network/API/HomeAPI.swift
  Maddori.Apple/Maddori.Apple/Network/EndPoint/HomeEndPoint.swift
  Maddori.Apple/Maddori.Apple/Network/Model/Request/CreateCssDTO.swift
  Maddori.Apple/Maddori.Apple/Network/Model/Request/SampleDTO.swift
  Maddori.Apple/Maddori.Apple/Network/Model/Response/Home/ResponseCreateCss.swift
  Maddori.Apple/Maddori.Apple/Network/Model/Response/Home/ResponseKeyword.swift
  Maddori.Apple/Maddori.Apple/Network/Service/APIEnvironment.swift
  Maddori.Apple/Maddori.Apple/Network/Service/APIService.swift
  Maddori.Apple/Maddori.Apple/Network/Service/EndPointable.swift
  Maddori.Apple/Maddori.Apple/Network/Service/HTTPMethod.swift
  Maddori.Apple/Maddori.Apple/Network/Service/NetworkError.swift
  Maddori.Apple/Maddori.Apple/Network/Service/NetworkRequest.swift
  Maddori.Apple/Maddori.Apple/Network/Service/Requestable.swift
  Maddori.Apple/Maddori.Apple/Screen/AddFeedbackContent/AddFeedbackContentViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/FromTo/FromToViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/HomeViewController.swift
Labels: ✨ Feature, 🙏 ASAP

#58 [FEAT] From To 위치 변경
  Maddori.Apple/Maddori.Apple/Global/Literal/TextLiteral.swift
  Maddori.Apple/Maddori.Apple/Screen/FromTo/FromToViewController.swift
Labels: ✨ Feature, 🙏 ASAP

#38 [ADD] 회고 시작 View 완성
  Maddori.Apple/Maddori.Apple.xcodeproj/project.pbxproj
  Maddori.Apple/Maddori.Apple/Global/Literal/ImageLiteral.swift
  Maddori.Apple/Maddori.Apple/Global/Literal/TextLiteral.swift
  Maddori.Apple/Maddori.Apple/Global/Resource/Assets.xcassets/calendar.imageset/Contents.json
  Maddori.Apple/Maddori.Apple/Global/Resource/Assets.xcassets/calendar.imageset/calendar.pdf
  Maddori.Apple/Maddori.Apple/Screen/AddReflection/AddReflectionViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/StartReflection/StartReflectionViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/StartReflection/UIComponent/CustomVisualEffectView.swift
Labels: ✨ Feature, 👏 Improvement, 🏖 Relax

#39 [FEAT] 초대코드 UI 구현
  Maddori.Apple/Maddori.Apple.xcodeproj/project.pbxproj
  Maddori.Apple/Maddori.Apple/Global/Literal/TextLiteral.swift
  Maddori.Apple/Maddori.Apple/Screen/Setup/InvitedCodeViewController.swift
Labels: ✨ Feature
