Repository DeveloperAcademy-POSTECH/MacC-Team-Maddori.Apple, pull requests merged in 2023-04, with the labels that each got.

#322 [ADD] 팀 정보 수정 화면 내 정보 구현 - 초대코드 공유, 팀 나가기 버튼 추가(4/4)
  Maddori.Apple/Maddori.Apple.xcodeproj/project.pbxproj
  Maddori.Apple/Maddori.Apple/Global/Extension/UIViewController+Extension.swift
  Maddori.Apple/Maddori.Apple/Global/Literal/TextLiteral.swift
  Maddori.Apple/Maddori.Apple/Global/Resource/Assets.xcassets/Person.imageset/Contents.json
  Maddori.Apple/Maddori.Apple/Global/Resource/Assets.xcassets/Person.imageset/Person.pdf
  Maddori.Apple/Maddori.Apple/Global/Resource/Assets.xcassets/Person.imageset/Person.svg
  Maddori.Apple/Maddori.Apple/Screen/Home/TeamDetail/Cell/TeamDetailMemberTableHeaderView.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/TeamDetail/Cell/TeamDetailMemberTableViewCell.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/TeamDetail/Cell/TeamDetailMembersCell.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/TeamDetail/TeamDetailViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/TeamDetail/UIComponent/FullDividerView.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/TeamDetail/UIComponent/MemberInformationView.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/TeamDetail/UIComponent/TeamDetailMembersView.swift
Labels: ✨ Feature

#324 [CHORE] loading indicator 추가
  Maddori.Apple/Maddori.Apple/Global/UIComponent/Button/MainButton.swift
  Maddori.Apple/Maddori.Apple/Screen/Setup/CreateTeam/CreateTeamViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/Setup/JoinTeam/JoinTeamViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/Setup/SetNickname/SetNicknameViewController.swift
Labels: 🛠 Chore

#327 [FEAT] 팀 상세 정보View API 연결
  Maddori.Apple/Maddori.Apple.xcodeproj/project.pbxproj
  Maddori.Apple/Maddori.Apple/Network/EndPoint/TeamDetailEndPoint.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/Home/HomeViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/TeamDetail/Cell/TeamDetailMemberTableHeaderView.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/TeamDetail/Cell/TeamDetailMemberTableViewCell.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/TeamDetail/TeamDetailViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/TeamDetail/UIComponent/MemberInformationView.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/TeamDetail/UIComponent/TeamDetailMembersView.swift
Labels: ✨ Feature, 📡 API

#330 [CHORE] 건너뛰기 버튼 삭제
  Maddori.Apple/Maddori.Apple/Global/Literal/TextLiteral.swift
  Maddori.Apple/Maddori.Apple/Screen/Setup/JoinTeam/JoinTeamViewController.swift
Labels: 🛠 Chore

#333 [CHORE] Id가 맡은 API 수정사항들 반영
  Maddori.Apple/Maddori.Apple/Network/EndPoint/HomeEndPoint.swift
  Maddori.Apple/Maddori.Apple/Network/EndPoint/MyReflectionEndPoint.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/Home/HomeViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/MyReflection/MyReflection/MyReflectionViewController.swift
Labels: 🛠 Chore, 📡 API

#337 [CHORE] api 주소 변경과 동시에 수정된 response 작업입니다.
  Maddori.Apple/Maddori.Apple/Network/EndPoint/MyReflectionEndPoint.swift
  Maddori.Apple/Maddori.Apple/Network/Response/FeedBackResponse.swift
Labels: 🛠 Chore, 📡 API

#328 [FEAT] 팀관리 뷰 api연결 PR입니다.
  Maddori.Apple/Maddori.Apple.xcodeproj/project.pbxproj
  Maddori.Apple/Maddori.Apple/Global/Extension/NotificationName+Extension.swift
  Maddori.Apple/Maddori.Apple/Network/EndPoint/TeamInfoEndPoint.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/Home/HomeViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/Home/TeamManageViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/Home/UIComponent/ChangeTeamView.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/Home/UIComponent/TeamChangeCollectionViewCell.swift
  Maddori.Apple/Maddori.Apple/Screen/Setup/CreateTeam/CreateTeamViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/Setup/JoinTeam/JoinTeamViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/Setup/Login/LoginViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/Setup/SetNickname/SetNicknameViewController.swift
Labels: ✨ Feature, 📡 API

#331 [CHORE] fetchCertainTeamDetail API ver2로 업데이트
  Maddori.Apple/Maddori.Apple/Network/EndPoint/HomeEndPoint.swift
  Maddori.Apple/Maddori.Apple/Network/Response/CertainTeamDetailResponse.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/Home/HomeViewController.swift
Labels: 🐞 Bugfix, 🛠 Chore

#343 [CHORE] 런치스크린 추가
  Maddori.Apple/Maddori.Apple.xcodeproj/project.pbxproj
  Maddori.Apple/Maddori.Apple/Global/Resource/Base.lproj/LaunchScreen.storyboard
  Maddori.Apple/Maddori.Apple/Screen/Setup/Launch/LaunchScreen.storyboard
Labels: 🛠 Chore

#340 [FEAT] 팀 이름 수정 View와 API 추가
  Maddori.Apple/Maddori.Apple.xcodeproj/project.pbxproj
  Maddori.Apple/Maddori.Apple/Global/Literal/TextLiteral.swift
  Maddori.Apple/Maddori.Apple/Network/EndPoint/EditTeamNameEndPoint.swift
  Maddori.Apple/Maddori.Apple/Network/Reqeust/DTO/EditTeamNameDTO.swift
  Maddori.Apple/Maddori.Apple/Network/Response/EditTeamNameResponse.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/EditTeamName/EditTeamNameViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/Home/HomeViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/TeamDetail/TeamDetailViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/TeamDetail/UIComponent/TeamDetailMembersView.swift
Labels: ✨ Feature, 📡 API

#342 [ADD] 초대코드 복사하기 ToastView 컴포넌트화 완료
  Maddori.Apple/Maddori.Apple.xcodeproj/project.pbxproj
  Maddori.Apple/Maddori.Apple/Global/Literal/TextLiteral.swift
  Maddori.Apple/Maddori.Apple/Global/UIComponent/View/ToastContentView.swift
  Maddori.Apple/Maddori.Apple/Global/UIComponent/View/ToastView.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/TeamDetail/TeamDetailViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/Setup/InvitationCode/InvitationCodeViewController.swift
Labels: ✨ Feature, 👏 Improvement

#347 [FEAT] 피드백 줄 때 맴버 선택 뷰 UI 변경
  Maddori.Apple/Maddori.Apple/Global/UIComponent/CollectionView/MemberCollectionView/MemberCollectionView.swift
  Maddori.Apple/Maddori.Apple/Global/UIComponent/CollectionView/MemberCollectionView/MemberCollectionViewCell.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/AddFeedback/AddDetailFeedback/AddFeedbackDetailViewController.swift
Labels: ✨ Feature
