Repository DeveloperAcademy-POSTECH/MacC-Team-Maddori.Apple, pull requests merged in 2023-02, with the labels that each got.

#283 [ADD] 팀 정보 수정 화면 상단 타이틀 구현 (1/4)
  Maddori.Apple/Maddori.Apple.xcodeproj/project.pbxproj
  Maddori.Apple/Maddori.Apple/Global/Extension/UIButton+Extension.swift
  Maddori.Apple/Maddori.Apple/Global/Literal/TextLiteral.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/Home/HomeViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/TeamDetail/TeamDetailViewController.swift
Labels: ✨ Feature

#279 [ADD] SetNickname 바뀐 UI 구현
  Maddori.Apple/Maddori.Apple.xcodeproj/project.pbxproj
  Maddori.Apple/Maddori.Apple/Global/Extension/UIFont+Extension.swift
  Maddori.Apple/Maddori.Apple/Global/Extension/UILabel+Extension.swift
  Maddori.Apple/Maddori.Apple/Global/Literal/ImageLiteral.swift
  Maddori.Apple/Maddori.Apple/Global/Literal/TextLiteral.swift
  Maddori.Apple/Maddori.Apple/Global/Resource/Assets.xcassets/profileNone.imageset/Contents.json
  Maddori.Apple/Maddori.Apple/Global/Resource/Assets.xcassets/profileNone.imageset/profileNone.pdf
  Maddori.Apple/Maddori.Apple/Screen/Setup/SetNickname/SetNicknameViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/Setup/SetNickname/UIComponent/ProfileImageButton.swift
Labels: ✨ Feature

#291 [ADD] SetNickname - 프로필 사진 추가 기능 구현
  Maddori.Apple/Maddori.Apple.xcodeproj/project.pbxproj
  Maddori.Apple/Maddori.Apple/Global/Literal/ImageLiteral.swift
  Maddori.Apple/Maddori.Apple/Global/Literal/TextLiteral.swift
  Maddori.Apple/Maddori.Apple/Global/Resource/Assets.xcassets/plus.imageset/Contents.json
  Maddori.Apple/Maddori.Apple/Global/Resource/Assets.xcassets/plus.imageset/plus.pdf
  Maddori.Apple/Maddori.Apple/Screen/Setup/SetNickname/SetNicknameViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/Setup/SetNickname/UIComponent/ProfileImageButton.swift
Labels: ✨ Feature

#288 [ADD] JoinReflectionButton 새로운 UI 반영
  Maddori.Apple/Maddori.Apple/Global/Extension/UIView+Extension.swift
  Maddori.Apple/Maddori.Apple/Global/Literal/TextLiteral.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/Home/HomeViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/Home/UIComponent/JoinReflectionButton.swift
Labels: ✨ Feature, 🛠 Chore

#285 [CHORE] PR Template 수정
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 🛠 Chore

#290 [ADD] 팀 정보 수정 화면 내 정보 구현 (2/4)
  Maddori.Apple/Maddori.Apple/Global/Literal/ImageLiteral.swift
  Maddori.Apple/Maddori.Apple/Global/Literal/TextLiteral.swift
  Maddori.Apple/Maddori.Apple/Global/Resource/Assets.xcassets/DefaultProfile.imageset/Contents.json
  Maddori.Apple/Maddori.Apple/Global/Resource/Assets.xcassets/DefaultProfile.imageset/Group 48095761.pdf
  Maddori.Apple/Maddori.Apple/Screen/Home/TeamDetail/TeamDetailViewController.swift
Labels: ✨ Feature
