Repository DeveloperAcademy-POSTECH/MacC-Team-Maddori.Apple, pull requests merged in 2023-01, with the labels that each got.

#241 [CHORE] 키워드가 없을 때 cell 터치하면 피드백 추가로 이동하기
  Maddori.Apple/Maddori.Apple/Screen/Home/Home/HomeViewController.swift
Labels: 🛠 Chore

#245 [CHORE] JoinTeamVC에 있는 버그 및 수정사항 반영하기
  Maddori.Apple/Maddori.Apple/Global/Literal/TextLiteral.swift
  Maddori.Apple/Maddori.Apple/Global/UIComponent/TextField/CustomTextField.swift
  Maddori.Apple/Maddori.Apple/Screen/Setup/JoinTeam/JoinTeamViewController.swift
Labels: 🐞 Bugfix

#243 [CHORE] 닉네임에 이모티콘 들어가 있을 경우 Alert 띄워주기 + 추가 버그 해결
  Maddori.Apple/Maddori.Apple/Global/Literal/TextLiteral.swift
  Maddori.Apple/Maddori.Apple/Network/Storage/UserDefaultStorage.swift
  Maddori.Apple/Maddori.Apple/Screen/Setup/Login/LoginViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/Setup/SetNickname/SetNicknameViewController.swift
Labels: 🐞 Bugfix

#253 [BUG] 리더의 경우 키워드가 잘려서 보이는 버그 해결
  Maddori.Apple/Maddori.Apple/Global/Literal/TextLiteral.swift
  Maddori.Apple/Maddori.Apple/Global/UIComponent/CollectionView/KeywordCollectionView/KeywordCollectionViewFlowLayout.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/Home/HomeViewController.swift
Labels: 🐞 Bugfix

#257 [CHORE] 자잘자잘한 버그 해결
  Maddori.Apple/Maddori.Apple.xcodeproj/project.pbxproj
  Maddori.Apple/Maddori.Apple/Global/UIComponent/View/EmptyView/EmptyFeedbackView.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/AddFeedback/AddFeedbackViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/InProgress/InProgressViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/MyFeedback/MyFeedback/UIComponent/MyFeedbackCollectionView.swift
  Maddori.Apple/Maddori.Apple/Screen/MyReflection/MyReflection/Cell/TotalReflectionCell.swift
  Maddori.Apple/Maddori.Apple/Screen/MyReflection/MyReflectionDetail/Cell/MyReflectionDetailTableViewCell.swift
Labels: 🐞 Bugfix

#259 [CHORE] 팀이름에 특수문자 입력하지 못하도록 핸들링하기
  Maddori.Apple/Maddori.Apple/Global/Literal/TextLiteral.swift
  Maddori.Apple/Maddori.Apple/Screen/Setup/CreateTeam/CreateTeamViewController.swift
Labels: 🐞 Bugfix

#272 [ADD] 새로운 디자인의 InProgressDetailVC 구현
  Maddori.Apple/Maddori.Apple/Screen/Home/InProgressDetail/InProgressDetailViewController.swift
Labels: 🛠 Chore

#251 [ADD] 보관함 탭에서 멤버가 없을때 EmptyView 추가
  Maddori.Apple/Maddori.Apple.xcodeproj/project.pbxproj
  Maddori.Apple/Maddori.Apple/Global/Literal/ImageLiteral.swift
  Maddori.Apple/Maddori.Apple/Global/Literal/TextLiteral.swift
  Maddori.Apple/Maddori.Apple/Global/UIComponent/View/EmptyView/EmptyPersonView.swift
  Maddori.Apple/Maddori.Apple/Screen/MyFeedback/MyFeedback/MyFeedbackViewController.swift
Labels: ✨ Feature

#252 [FIX] 피드백 수정하기 상세 화면 스크롤 안되는 버그 해결
  Maddori.Apple/Maddori.Apple/Screen/MyFeedback/MyFeedbackDetail/MyFeedbackDetailViewController.swift
Labels: 🐞 Bugfix

#264 [CHORE] 피그마와 다른 UI/색 수정하기, 멤버가 5명 이상 되는 경우 멤버 최하단 CollectionViewCell 이 가려지는 버그 해결하기
  Maddori.Apple/Maddori.Apple/Global/UIComponent/CollectionView/MemberCollectionView/MemberCollectionView.swift
  Maddori.Apple/Maddori.Apple/Global/UIComponent/CollectionView/MemberCollectionView/MemberCollectionViewCell.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/Home/AddDetailFeedback/AddDetailFeedbackViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/Home/AddDetailFeedback/UIComponent/SelectKeywordTypeView.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/Home/AddDetailFeedback/UIComponent/SelectMemberView.swift
Labels: 🐞 Bugfix, 🏖 Relax, 🛠 Chore

#266 [CHORE] 멤버를 터치한 후 피드백 종류 drop down 되도록 하기
  Maddori.Apple/Maddori.Apple/Global/UIComponent/View/FeedbackTypeButtonView.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/Home/AddDetailFeedback/AddDetailFeedbackViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/Home/AddDetailFeedback/UIComponent/SelectKeywordTypeView.swift
Labels: 🏖 Relax, 🛠 Chore

#270 [ADD] 눌렀던 피드백 상태를 저장해서 다른 뷰에 다녀와도 그 상태가 유지되도록 구현하기
  Maddori.Apple/Maddori.Apple/Global/UIComponent/CollectionView/KeywordCollectionView/KeywordCollectionViewCell.swift
  Maddori.Apple/Maddori.Apple/Global/UIComponent/CollectionView/MemberCollectionView/MemberCollectionView.swift
  Maddori.Apple/Maddori.Apple/Global/UIComponent/CollectionView/MemberCollectionView/MemberCollectionViewCell.swift
  Maddori.Apple/Maddori.Apple/Network/Model/Keyword/Keyword.swift
  Maddori.Apple/Maddori.Apple/Network/Storage/UserDefaultHandler.swift
  Maddori.Apple/Maddori.Apple/Network/Storage/UserDefaultStorage.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/Home/HomeViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/InProgress/InProgressViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/SelectReflectionMember/SelectReflectionMemberViewController.swift
Labels: 🛠 Chore

#263 [CHORE] AddDetailFeedback VC 명칭 변경하기
  Maddori.Apple/Maddori.Apple.xcodeproj/project.pbxproj
  Maddori.Apple/Maddori.Apple/Screen/Home/AddFeedback/AddDetailFeedback/AddFeedbackDetailViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/AddFeedback/AddDetailFeedback/Model/FeedbackContent.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/AddFeedback/AddDetailFeedback/UIComponent/SelectKeywordTypeView.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/AddFeedback/AddDetailFeedback/UIComponent/SelectMemberView.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/Home/HomeViewController.swift
Labels: 🏖 Relax, 🛠 Chore

#273 [CHORE] v1.3.1에 따른 main 브랜치 업데이트
  Maddori.Apple/Maddori.Apple.xcodeproj/project.pbxproj
  Maddori.Apple/Maddori.Apple/Global/Literal/ImageLiteral.swift
  Maddori.Apple/Maddori.Apple/Global/Literal/TextLiteral.swift
  Maddori.Apple/Maddori.Apple/Global/UIComponent/CollectionView/KeywordCollectionView/KeywordCollectionViewCell.swift
  Maddori.Apple/Maddori.Apple/Global/UIComponent/CollectionView/KeywordCollectionView/KeywordCollectionViewFlowLayout.swift
  Maddori.Apple/Maddori.Apple/Global/UIComponent/CollectionView/MemberCollectionView/MemberCollectionView.swift
  Maddori.Apple/Maddori.Apple/Global/UIComponent/CollectionView/MemberCollectionView/MemberCollectionViewCell.swift
  Maddori.Apple/Maddori.Apple/Global/UIComponent/TextField/CustomTextField.swift
  Maddori.Apple/Maddori.Apple/Global/UIComponent/View/EmptyView/EmptyFeedbackView.swift
  Maddori.Apple/Maddori.Apple/Global/UIComponent/View/EmptyView/EmptyPersonView.swift
  Maddori.Apple/Maddori.Apple/Global/UIComponent/View/FeedbackTypeButtonView.swift
  Maddori.Apple/Maddori.Apple/Network/Model/Keyword/Keyword.swift
  Maddori.Apple/Maddori.Apple/Network/Storage/UserDefaultHandler.swift
  Maddori.Apple/Maddori.Apple/Network/Storage/UserDefaultStorage.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/AddFeedback/AddDetailFeedback/AddFeedbackDetailViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/AddFeedback/AddDetailFeedback/Model/FeedbackContent.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/AddFeedback/AddDetailFeedback/UIComponent/SelectKeywordTypeView.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/AddFeedback/AddDetailFeedback/UIComponent/SelectMemberView.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/AddFeedback/AddFeedbackViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/Home/HomeViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/InProgress/InProgressViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/InProgressDetail/InProgressDetailViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/SelectReflectionMember/SelectReflectionMemberViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/MyFeedback/MyFeedback/Cell/MyFeedbackCollectionViewCell.swift
  Maddori.Apple/Maddori.Apple/Screen/MyFeedback/MyFeedback/MyFeedbackViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/MyFeedback/MyFeedback/UIComponent/MyFeedbackCollectionView.swift
  Maddori.Apple/Maddori.Apple/Screen/MyFeedback/MyFeedbackDetail/MyFeedbackDetailViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/MyReflection/MyReflection/Cell/TotalReflectionCell.swift
  Maddori.Apple/Maddori.Apple/Screen/MyReflection/MyReflectionDetail/Cell/MyReflectionDetailTableViewCell.swift
  Maddori.Apple/Maddori.Apple/Screen/MyReflection/MyReflectionFeedback/MyReflectionFeedbackViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/Setup/CreateTeam/CreateTeamViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/Setup/JoinTeam/JoinTeamViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/Setup/Login/LoginViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/Setup/SetNickname/SetNicknameViewController.swift
  Maddori.Apple/Settings.bundle/Root.plist
  Maddori.Apple/Settings.bundle/com.mono0926.LicensePlist.latest_result.txt
  Maddori.Apple/Settings.bundle/com.mono0926.LicensePlist.plist
  Maddori.Apple/Settings.bundle/com.mono0926.LicensePlist/Alamofire.plist
  Maddori.Apple/Settings.bundle/com.mono0926.LicensePlist/SnapKit.plist
  Maddori.Apple/Settings.bundle/en.lproj/Root.strings
Labels: Main

#276 [ADD] HomeView 상단 바뀐 UI 우선 적용
  Maddori.Apple/Maddori.Apple/Global/Literal/ImageLiteral.swift
  Maddori.Apple/Maddori.Apple/Global/Literal/SizeLiteral.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/Home/HomeViewController.swift
Labels: ✨ Feature, 🙏 ASAP, 🛠 Chore

#287 [CHORE] 개발용 서버로 변경
  Maddori.Apple/Maddori.Apple/Global/Literal/UrlLiteral.swift
Labels: 🙏 ASAP
