Repository DeveloperAcademy-POSTECH/MacC-Team-Maddori.Apple, pull requests merged in 2023-03, with the labels that each got.

#301 [ADD] Setup Navigation/api 반영 & 공유하기 기능 구현
  Maddori.Apple/Maddori.Apple/Global/Extension/String+Extension.swift
  Maddori.Apple/Maddori.Apple/Global/Literal/TextLiteral.swift
  Maddori.Apple/Maddori.Apple/Global/Literal/UrlLiteral.swift
  Maddori.Apple/Maddori.Apple/Global/UIComponent/View/AlertViewController.swift
  Maddori.Apple/Maddori.Apple/Network/EndPoint/SetupEndPoint.swift
  Maddori.Apple/Maddori.Apple/Network/Reqeust/DTO/CreateTeamDTO.swift
  Maddori.Apple/Maddori.Apple/Network/Reqeust/DTO/JoinTeamDTO.swift
  Maddori.Apple/Maddori.Apple/Network/Response/CreateTeamResponse.swift
  Maddori.Apple/Maddori.Apple/Network/Response/JoinTeamResponse.swift
  Maddori.Apple/Maddori.Apple/Network/Response/MemberResponse.swift
  Maddori.Apple/Maddori.Apple/Network/Response/TeamInfoResponse.swift
  Maddori.Apple/Maddori.Apple/Network/Storage/UserDefaultHandler.swift
  Maddori.Apple/Maddori.Apple/Network/Storage/UserDefaultStorage.swift
  Maddori.Apple/Maddori.Apple/Screen/MyReflection/MyReflection/MyReflectionViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/Setup/CreateTeam/CreateTeamViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/Setup/InvitationCode/InvitationCodeViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/Setup/JoinTeam/JoinTeamViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/Setup/Login/LoginViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/Setup/SetNickname/SetNicknameViewController.swift
Labels: ✨ Feature

#294 [CHORE] blurview not showing bugfix
  Maddori.Apple/Maddori.Apple/Screen/Home/Home/HomeViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/SelectReflectionMember/SelectReflectionMemberViewController.swift
Labels: 🐞 Bugfix, 🛠 Chore

#298 [ADD] 건너뛰기 용 homeVC 편집
  Maddori.Apple/Maddori.Apple/Global/Literal/TextLiteral.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/Home/HomeViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/Home/UIComponent/JoinReflectionButton.swift
Labels: 🛠 Chore

#302 [FEAT] 팀 설정 모달창 UI (1/4)
  Maddori.Apple/Maddori.Apple.xcodeproj/project.pbxproj
  Maddori.Apple/Maddori.Apple/Screen/Home/Home/HomeViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/Home/TeamManageViewController.swift
Labels: ✨ Feature

#296 [ADD] 회고 일정 변경 기능 추가
  Maddori.Apple/Maddori.Apple.xcodeproj/project.pbxproj
  Maddori.Apple/Maddori.Apple/Global/Extension/String+Extension.swift
  Maddori.Apple/Maddori.Apple/Global/Literal/TextLiteral.swift
  Maddori.Apple/Maddori.Apple/Global/UIComponent/Button/DeleteButton.swift
  Maddori.Apple/Maddori.Apple/Network/EndPoint/CreateReflectionEndPoint.swift
  Maddori.Apple/Maddori.Apple/Network/Response/DeleteReflectionResponse.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/CreateReflection/CreateReflectionViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/Home/HomeViewController.swift
Labels: ✨ Feature, 🛠 Chore

#303 [FEAT] 팀 설정 모달창 UI (2/4)
  Maddori.Apple/Maddori.Apple.xcodeproj/project.pbxproj
  Maddori.Apple/Maddori.Apple/Screen/Home/Home/Model/Option.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/Home/Model/Section.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/Home/TeamManageSettingCell.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/Home/TeamManageViewController.swift
Labels: ✨ Feature

#306 [ADD] 팀 정보 수정 화면 내 정보 구현 - 멤버 리스트 추가(3/4)
  Maddori.Apple/Maddori.Apple.xcodeproj/project.pbxproj
  Maddori.Apple/Maddori.Apple/Global/Resource/Assets.xcassets/Person.imageset/Contents.json
  Maddori.Apple/Maddori.Apple/Global/Resource/Assets.xcassets/Person.imageset/Person.pdf
  Maddori.Apple/Maddori.Apple/Global/Resource/Assets.xcassets/Person.imageset/Person.svg
  Maddori.Apple/Maddori.Apple/Screen/Home/TeamDetail/Cell/TeamDetailMembersCell.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/TeamDetail/TeamDetailViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/TeamDetail/UIComponent/MemberInformationView.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/TeamDetail/UIComponent/TeamDetailMembersView.swift
Labels: ✨ Feature

#317 [ADD] 프로필 이미지 api 연결
  Maddori.Apple/Maddori.Apple.xcodeproj/project.pbxproj
  Maddori.Apple/Maddori.Apple/Global/Extension/UIImageView+Extension.swift
  Maddori.Apple/Maddori.Apple/Global/Literal/UrlLiteral.swift
  Maddori.Apple/Maddori.Apple/Global/UIComponent/CollectionView/MemberCollectionView/MemberCollectionView.swift
  Maddori.Apple/Maddori.Apple/Network/EndPoint/AddFeedBackEndPoint.swift
  Maddori.Apple/Maddori.Apple/Network/EndPoint/InProgressEndPoint.swift
  Maddori.Apple/Maddori.Apple/Network/EndPoint/MyFeedBackEndPoint.swift
  Maddori.Apple/Maddori.Apple/Network/Response/CurrentMemberResponse.swift
  Maddori.Apple/Maddori.Apple/Network/Storage/ImageCacheManager.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/AddFeedback/AddDetailFeedback/UIComponent/SelectMemberView.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/SelectReflectionMember/ReflectionMember/ReflectionMemberCollectionView.swift
  Maddori.Apple/Maddori.Apple/Screen/MyFeedback/MyFeedback/Cell/MyFeedbackMemberCollectionViewCell.swift
  Maddori.Apple/Maddori.Apple/Screen/MyFeedback/MyFeedback/MyFeedbackViewController.swift
Labels: 🛠 Chore, 📡 API

#319 [FEAT] 팀 관리 모달 UI 완성
  Maddori.Apple/Maddori.Apple.xcodeproj/project.pbxproj
  Maddori.Apple/Maddori.Apple/Global/Literal/ImageLiteral.swift
  Maddori.Apple/Maddori.Apple/Global/Literal/TextLiteral.swift
  Maddori.Apple/Maddori.Apple/Global/Resource/Assets.xcassets/team.imageset/Contents.json
  Maddori.Apple/Maddori.Apple/Global/Resource/Assets.xcassets/team.imageset/team.pdf
  Maddori.Apple/Maddori.Apple/Screen/Home/Home/TeamManageViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/Home/UIComponent/ChangeTeamView.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/Home/UIComponent/EmptyTeamView.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/Home/UIComponent/TeamChangeCollectionViewCell.swift
Labels: ✨ Feature
