Repository DeveloperAcademy-POSTECH/MacC-Team-Maddori.Apple, pull requests merged in 2023-05, with the labels that each got.

#362 [CHORE] 회원탈퇴/로그아웃 버튼 삭제하기
  Maddori.Apple/Maddori.Apple/Global/Literal/TextLiteral.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/Home/TeamManageViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/MyReflection/MyReflection/MyReflectionViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/MyReflection/MyReflectionDetail/MyReflectionDetailViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/MyReflection/MyReflectionFeedback/MyReflectionFeedbackViewController.swift
Labels: 🛠 Chore

#364 [BUGFIX] 자신에게 피드백 줄 수 없도록 수정
  Maddori.Apple/Maddori.Apple/Screen/Home/AddFeedback/AddDetailFeedback/AddFeedbackDetailViewController.swift
Labels: 🐞 Bugfix

#367 [FEAT] 키보드 위로스크롤시 내리기 기능을 추가했습니다.
  Maddori.Apple/Maddori.Apple/Screen/Home/AddFeedback/AddFeedbackContentViewController.swift
Labels: ✨ Feature, 🛠 Chore

#349 [CHORE] MainButton에 Gradient를 적용했습니다.
  Maddori.Apple/Maddori.Apple/Global/UIComponent/Button/MainButton.swift
Labels: 🛠 Chore

#353 [CHORE] 팀 이름 수정 View에서 NavigationBar가 사라지는 문제 해결
  Maddori.Apple/Maddori.Apple/Screen/Home/Home/HomeViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/TeamDetail/TeamDetailViewController.swift
Labels: 🛠 Chore

#375 [BUGFIX] 닉네임 수정되도록 변경
  Maddori.Apple/Maddori.Apple/Network/Response/TeamNameResponse.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/Home/UIComponent/ChangeTeamView.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/TeamDetail/TeamDetailViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/MyReflection/MyReflection/MyReflectionViewController.swift
Labels: 🐞 Bugfix

#377 [CHORE] 폴더 위치 변경
  Maddori.Apple/Maddori.Apple.xcodeproj/project.pbxproj
  Maddori.Apple/Maddori.Apple/Screen/Home/TeamManage/Cell/TeamManageSettingCell.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/TeamManage/Model/Option.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/TeamManage/Model/Section.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/TeamManage/TeamManageViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/TeamManage/UIComponent/ChangeTeamView.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/TeamManage/UIComponent/EmptyTeamView.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/TeamManage/UIComponent/TeamChangeCollectionViewCell.swift
Labels: 🛠 Chore

#380 [FEAT] 맴버 선택 화면에서 맴버가 없을 시 emptyView 설정
  Maddori.Apple/Maddori.Apple/Global/Literal/TextLiteral.swift
  Maddori.Apple/Maddori.Apple/Global/UIComponent/CollectionView/MemberCollectionView/MemberCollectionView.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/AddFeedback/AddDetailFeedback/UIComponent/SelectMemberView.swift
Labels: 🛠 Chore

#382 [BUGFIX] 있던 팀을 다 나갔을 때 팀 선택 view 의 emptyview 깨짐 버그 수정
  Maddori.Apple/Maddori.Apple/Screen/Home/TeamManage/TeamManageViewController.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/TeamManage/UIComponent/ChangeTeamView.swift
Labels: 🐞 Bugfix

#355 [CHORE] TeamDetailView 에 empty view 추가
  Maddori.Apple/Maddori.Apple/Screen/Home/TeamDetail/UIComponent/TeamDetailMembersView.swift
Labels: 🐞 Bugfix, 🛠 Chore

#370 [CHORE] MyFeedbackVC Emptyview 중앙정렬
  Maddori.Apple/Maddori.Apple/Global/UIComponent/View/EmptyView/EmptyFeedbackView.swift
  Maddori.Apple/Maddori.Apple/Screen/MyFeedback/MyFeedback/UIComponent/MyFeedbackCollectionView.swift
Labels: 🐞 Bugfix

#385 [BUGFIX] 내 프로필 편집시 왔다갔다 했을때 이미지가 재사용되는 문제를 해결했습니다
  Maddori.Apple/Maddori.Apple/Screen/Home/TeamDetail/Cell/TeamDetailMemberTableViewCell.swift
Labels: 🐞 Bugfix

#372 [CHORE] 회고가 시작되었을 때 키워드가 없는 상황 추가
  Maddori.Apple/Maddori.Apple/Global/Literal/TextLiteral.swift
  Maddori.Apple/Maddori.Apple/Screen/Home/Home/HomeViewController.swift
Labels: 🐞 Bugfix, 🛠 Chore

#390 [CHORE] 카메라, 사진 접근 메시지 추가
  Maddori.Apple/Maddori.Apple.xcodeproj/project.pbxproj
Labels: 🙏 ASAP
